project:
  type: book
  execute-dir: project

book:
  google-analytics: "G-MMK8CF9JC0"
  title: "Research Design in the Social Sciences"
  subtitle: "Declaration, Diagnosis, and Redesign"
  margin-header: >
    <p align='center'><a style = 'color: black; text-decoration: none; font-size: 17px' target='_new' href='https://press.princeton.edu/books/paperback/9780691199573/research-design-in-the-social-sciences'>
    <img style='border: 1px solid darkgray; margin-bottom: 5px' width = 100px src='/figures/cover.jpg'><br/>Buy book</a></p>
  author:
    - Graeme Blair
    - Alexander Coppock
    - Macartan Humphreys
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - authors.qmd
    - part: "Introduction"
      chapters:
        - introduction/preface.qmd
        - introduction/what-is-a-research-design.qmd
        - introduction/research-design-principles.qmd
        - introduction/getting-started.qmd
    - part: "Declaration, Diagnosis, Redesign"
      chapters:
        - declaration-diagnosis-redesign/declaring-designs.qmd
        - declaration-diagnosis-redesign/specifying-model.qmd
        - declaration-diagnosis-redesign/defining-inquiry.qmd
        - declaration-diagnosis-redesign/crafting-data-strategy.qmd
        - declaration-diagnosis-redesign/choosing-answer-strategy.qmd
        - declaration-diagnosis-redesign/diagnosing-designs.qmd
        - declaration-diagnosis-redesign/redesigning.qmd
        - declaration-diagnosis-redesign/design-example.qmd
        - declaration-diagnosis-redesign/declaration-in-code.qmd
    - part: "Library"
      chapters:
        - library/index.qmd
        - library/observational-descriptive.qmd
        - library/observational-causal.qmd
        - library/experimental-descriptive.qmd
        - library/experimental-causal.qmd
        - library/complex.qmd
    - part: "Lifecycle"
      chapters:
        - lifecycle/index.qmd
        - lifecycle/planning.qmd
        - lifecycle/realization.qmd
        - lifecycle/integration.qmd
    - epilogue.qmd
    - references.qmd
    - appendix.qmd
    - student-teacher.qmd
    - errata.qmd

  sidebar:
    - style: "floating"
      collapse-level: 2
      align: left
      contents:
        - authors.qmd
        - acknowledgements.qmd
        - section: "Introduction"
          contents:
            - introduction/preface.qmd
            - introduction/what-is-a-research-design.qmd
            - introduction/research-design-principles.qmd
            - introduction/getting-started.qmd
        - section: "Declaration, Diagnosis, Redesign"
          contents:
            - declaration-diagnosis-redesign/declaring-designs.qmd
            - declaration-diagnosis-redesign/specifying-model.qmd
            - declaration-diagnosis-redesign/defining-inquiry.qmd
            - declaration-diagnosis-redesign/crafting-data-strategy.qmd
            - declaration-diagnosis-redesign/choosing-answer-strategy.qmd
            - declaration-diagnosis-redesign/diagnosing-designs.qmd
            - declaration-diagnosis-redesign/redesigning.qmd
            - declaration-diagnosis-redesign/design-example.qmd
            - declaration-diagnosis-redesign/declaration-in-code.qmd
        - section: "Research design library"
          href: library/
          contents:
            - library/observational-descriptive.qmd
            - library/observational-causal.qmd
            - library/experimental-descriptive.qmd
            - library/experimental-causal.qmd
            - library/complex.qmd
        - section: "Research design lifecycle"
          href: lifecycle/
          contents:
          - lifecycle/planning.qmd
          - lifecycle/realization.qmd
          - lifecycle/integration.qmd
        - epilogue.qmd
        - references.qmd
        - appendix.qmd
        - student-teacher.qmd
        - errata.qmd

bibliography: references.bib

knitr:
  opts_chunk:
    collapse: true
    warning: false
    message: false
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true

language:
  crossref-def-title: "Declaration"
  crossref-lem-title: "Diagnosis"
  crossref-exm-title: "Principle"

format:
  html:
    theme: cosmo
    lightbox: true
    # number-offset: -1
    default-image-extension: svg
    code-link: true
    include-in-header:
      - header-additions.html
    include-before-body: buy-book.html
    template-partials:
      - partials/toc.html
    # self-contained: true
    # self-contained-math: true
  # pdf:
  #   documentclass: book
  #   default-image-extension: pdf



