project:
  type: book
  execute-dir: project

book:
  title: "Research Design"
  subtitle: "Declaration, Diagnosis, Redesign"
  author: "Graeme Blair, Alexander Coppock, and Macartan Humphreys"
  date: "6/20/2022"
  page-footer: "Copyright 2022 Graeme Blair, Alexander Coppock, and Macartan Humphreys" 
  chapters:
    - index.qmd

bibliography: references.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true
      
  
format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: book



