# Acknowledgements {-}

We are grateful to have worked with Jasper Cooper for six years on the ideas and tools introduced in this book. His words, ideas, and voice echo throughout the entire project.

Each of us inflicted early versions of DeclareDesign and our ideas about research design on our students and colleagues at UCLA, Yale,  Columbia, and WZB Berlin,  and at many summer schools and workshops. We thank our students for their patience and feedback on the tools and approach, which deeply shaped what you find in this book.

We held a book conference over Zoom and are grateful for the incisive feedback of Dorothy Bishop, Don Green, Nahomi Ichino, Kosuke Imai, Gary King, Andy Gelman, Felix Elwert, Molly Roberts, Cyrus Samii, and Rocio Titiunik. For feedback at our EGAP feedback session on Part I and Part IV, we thank Adam Berinsky, Jake Bowers, David Broockman, Cesi Cruz, Ryan Enos, Alex Hartman, Morgan Holmes, Ryan Moore, Pia Raffler, Dan Rubenson, and Rebecca Wolfe. We also thank the three anonymous reviewers of the manuscript for generous and helpful feedback.

A core part of the DeclareDesign project is its software implementation in R. We were lucky to work with a big group of talented graduate students and programmers on nearly every aspect of it. We are grateful to Neal Fultz who moved the software from prototype to professional software product and who made many big contributions to how the tools work now. Luke Sonnet is responsible for the speed and technical workings of estimatr; Aaron Rudkin for many ideas in fabricatr; Clara Bicalho, Markus Konrad, and Sisi Huang for DeclareDesignWizard; and Clara Bicalho and Lily Medina for DesignLibrary.

We are grateful to the many people who have intensively used the software in its early versions for their generous feedback, Tom Leavitt, Daniel Rubenson, Vartika Savarna, Tara Slough, Georgiy Syunyaev, Anna Wilke, Linan Yao. Special thanks also to Dorothy Bishop and Jake Bowers for so many thoughts and suggestions. 

We are grateful to the Laura and John Arnold Foundation, and especially Stuart Buck, for seeing the virtues of our approach and providing early funding of the project. We also thank EGAP for seed funding that got us started. We thank Lynn Vavreck for offering Alex a Hoffenberg Visiting Fellowship at UCLA to work on the software and an early version of the manuscript.

We thank Bridget Flannery-McCoy for shepherding this book to fruition and for her willingness to engage with us about offering a free online version of the book. We are also grateful to Eric Crahan for our early conversations about the idea for the book. 

Finally, Graeme and Alex thank Alex's spouse Penelope Van Grinsven for warmly putting up with us for a semester in Los Angeles and a year in New Haven and many coworking sessions in the pottery studio. 
