# About the authors {.unnumbered}

**Graeme Blair** is an assistant professor of political science at UCLA and serves as Co-Director of Training and Methods of Evidence and Governance and Politics (EGAP). Graeme uses experiments, field research, and statistics to study how to reduce violence and how to improve social science research. He works primarily in Nigeria, often in partnership with government, civil society, or international organizations. His work is published in journals including Science, Proceedings of the National Academy of Sciences, Science Advances, American Political Science Review, American Journal of Political Science, Journal of Politics, Journal of the American Statistical Association, and Political Analysis. His book manuscript on community policing is under advance contract with Cambridge University Press and his book on research design is forthcoming with Princeton University Press. He is the recipient of the Leamer-Rosenthal Prize for Open Social Science, the Society for Political Methodology best statistical software award, and the Pi Sigma Alpha best paper award.

**Alexander Coppock** is an assistant professor of political science at Yale University and a resident fellow of the Institution for Social Policy Studies and Center for the Study of American Politics. He received his Ph.D. in political science from Columbia University (2016). His principal research interest lies in political persuasion and its implications for the malleability of public opinion in the context of elections. His interests extend beyond persuasion to the design and analysis of randomized experiments.

**Macartan Humphreys** is a professor of political science at Columbia University and director of the Institutions and Political Inequality group at the WZB Berlin. He works on the political economy of development. Ongoing research focuses on post-conflict development, ethnic politics, political authority and leadership, and democratic development with a current focus on the use of field experiments to study democratic decision-making in post-conflict and developing areas. Macartan has worked in Chad, Ghana, Haiti, Indonesia, Liberia, Mali, Sao Tome and Principe, Sierra Leone, Senegal, Uganda, and elsewhere. Recent work has appeared in the American Political Science Review, Journal of Development Economics, Science Advances, and elsewhere. He has written or coauthored books on ethnic politics, natural resource management, and game theory and politics. Humphreys is a former Trudeau fellow and scholar of the Harvard Academy.