# Errata {.unnumbered}

These errata are errors in the printed book. These changes are implemented in this online version.

- On pg. 53, footnote 1: "Here we are referring to an 'inquiry model' not a 'reference model,' as discussed in Section 2.2.1" should read "Here we are referring to an 'inquiry model' not a 'reference model,' as discussed in Section 2.1.1".
- On pg. 69, Table 8.1, row 1 now reads `simple_rs(N = 100, prob = .25)` instead of `simple_rs(N = 100, p = .25)`; row 2 now reads `complete_rs(N = 100, n = 25)` instead of `simple_rs(N = 100, p = 0.25)`; row 4: `cluster_ra` should be `cluster_rs`; and in row 6, `cluster_ra` should be `cluster_rs` and `strata_ra` should be `strata_rs`. Thanks to Bjorn Van Campenhout for identifying the first two errors.
- On pg. 101: "The $p$-value is the probability this also goes with the misplaced section estimates of 15 or larger" should read "The $p$-value is the probability under the null model of obtaining estimates of 15 or larger."
- On pg. 158: The second code block, which includes the code `MASS::mvrnorm`, should read `n = 1000` not `N = 1000`.
- On pgs. 221-224: We corrected an error in Declaration 16.5 and Declaration 16.6 that erroneously switched the values of the treated and control potential outcomes when X = 0 with the values when X is at the cutoff. We modified Declaration 16.5 and Figure 16.9 to describe the design with respect to the cutoff and updated the figure caption and text to reflect these changes.
- On pg. 225: The last line of the code was changed from `diagnose_designs` to `diagnose_designs()`.
- On pg. 26: "In part IV on the research design lifecycle" should read "In Part IV on the research design lifecycle".
- On pg. 53: "These complex inquires are made up of a series of atomic inquiries" should read "These complex inquiries are made up of a series of atomic inquiries".
- On pg. 237: "conjoint experiments target descriptive, rather than casual, inquiries" should read "rather than causal, inquiries".
- On pg. 273: "the local average treatment effect (LATE) described in Chapter 16.4" should read "described in Section 16.4".
- On pg. 309: "how leaders allocate cabinet positions to bolseter coalitions" should read "to bolster coalitions".
- On pg. 340: "They also told us also that they believed" should read "They also told us that they believed".
- On pg. 343: in the quotation from Bonilla and Tillery (2020), "other pertinent moderations beyond gender and LGBTQ+ status" should read "other pertinent moderators beyond gender and LGBTQ+ status".
- On pg. 348: "covey the entirety of *MIDA* in one sentence" should read "convey the entirety of *MIDA* in one sentence".
- On pgs. 124-125: We removed a reference to the power formula from Gerber and Green (2012). We now discuss a generic restatement of statistical power.

*Due to final copyediting by the Press, the website version may differ slightly from the print version. If you discover a discrepency, please email us at graeme.blair@gmail.com, acoppock@gmail.com, and macartan@gmail.com and we will fix it and send you DeclareDesign stickers!*

## Substantive changes

- On pg. 210-211, we changed the inquiry to be the ATT rather than the ATE, to reflect the more common practice of targeting the ATT in matching designs. Declaration 16.2 now declares the ATT as the inquiry; we now write "Our inquiry is the average treatment effect on the treated (ATT). This is the average treatment effect among the units who are in fact treated."; and Figure 16.4 is updated to reflect the change in the x-axis title. 

## Code updates

We are committed to maintaining the code in this book as the R ecosystem evolves. The following changes reflect differences between the printed book and the online version. 

- On pg. 103, Declaration 9.3 now reads `.summary = ~tidy(., exponentiate = TRUE)` instead of `.summary = ~tidy_stan(., exponentiate = TRUE)`, reflecting the use of the standard `broom.mixed` package for tidying stan objects. In addition, the library `rdss` is replaced with the library `broom.mixed` in the declaration.
- On pg. 212-213, Declaration 16.3 now uses updated syntax from the `DIDmultiplegt` package, specifically `mode = 'old'` is added. We also add `Sys.setenv(RGL_USE_NULL = TRUE)` to address package dependency issues.
