<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Research Design in the Social Sciences - 10&nbsp; Diagnosing designs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../declaration-diagnosis-redesign/design-example.html" rel="next">
<link href="../declaration-diagnosis-redesign/redesigning.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><style type="text/css" media="print">
    body { visibility: hidden; display: none }
</style>
<script type="text/javascript">
    function createCookie(name, value, days) {
        var expires;
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (7 * 24 * 60 * 60 * 1000));
            expires = "; expires=" + date.toGMTString();
        }
        else {
            expires = "";
        }
        document.cookie = name + "=" + value + expires + "; path=/";
    }
    
    function getCookie(c_name) {
        if (document.cookie.length > 0) {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1) {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) {
                    c_end = document.cookie.length;
                }
                return unescape(document.cookie.substring(c_start, c_end));
            }
        }
        return "";
    }
    window.onload = () => {
      if (getCookie('popupShown') != 'yes') {
        const myModal = new bootstrap.Modal('#exampleModal');
        myModal.show();
        createCookie('popupShown', 'yes', 1)
      }
    }
</script><script src="../site_libs/kePrint-0.0.1/kePrint.js"></script><link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diagnosing designs</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Research Design in the Social Sciences</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../authors.html" class="sidebar-item-text sidebar-link">About the authors</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../acknowledgements.html" class="sidebar-item-text sidebar-link">Acknowledgements</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Introduction</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/what-is-a-research-design.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">What is a research design?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/research-design-principles.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Research design principles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/getting-started.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Getting started</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Declaration, Diagnosis, Redesign</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/declaring-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Declaring designs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/specifying-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Specifying the model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/defining-inquiry.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Defining the inquiry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/crafting-research-strategy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Crafting a data strategy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/choosing-answer-strategy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Choosing an answer strategy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/redesigning.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Redesigning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/diagnosing-designs.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diagnosing designs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/design-example.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Design example</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/declaration-in-code.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Designing in code</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../library/" class="sidebar-item-text sidebar-link">Research design library</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../library/observational-descriptive/" class="sidebar-item-text sidebar-link">Observational : descriptive</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-descriptive/simple-random-sampling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simple random sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-descriptive/cluster-random-sampling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Cluster random sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-descriptive/multilevel-regression-poststratification.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multi-level regression and poststratification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-descriptive/index-creation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Index creation</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../library/observational-causal/" class="sidebar-item-text sidebar-link">Observational : causal</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-causal/process-tracing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Process tracing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-causal/selection-on-observables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Selection-on-observables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-causal/difference-in-differences.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Difference-in-differences</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-causal/instrumental-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Instrumental variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-causal/regression-discontinuity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Regression discontinuity designs</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../library/experimental-descriptive/" class="sidebar-item-text sidebar-link">Experimental : descriptive</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-descriptive/audit-experiments.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Audit experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-descriptive/list-experiments.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">List experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-descriptive/conjoint-experiments.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Conjoint experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-descriptive/behavioral-games.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Behavioral games</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../library/experimental-causal/" class="sidebar-item-text sidebar-link">Experimental : causal</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/two-arm-randomized-experiments.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Two-arm randomized experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/block-randomized-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Block-randomized experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/cluster-randomized-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Cluster-randomized experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/subgroup-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Subgroup designs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/factorial-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Factorial experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/encouragement-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Encouragement designs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/placebo-controlled-experiments.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Placebo-controlled experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/stepped-wedge-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Stepped-wedge experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/randomized-saturation-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Randomized saturation experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal/experiments-over-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Experiments over networks</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../library/complex/" class="sidebar-item-text sidebar-link">Complex</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/complex/discovery-causal-forests.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Discovery using causal forests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/complex/structural-estimation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Structural estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/complex/meta-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Meta-analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/complex/multi-site-studies.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Multi-site studies</span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../lifecycle/" class="sidebar-item-text sidebar-link">Research design lifecycle</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../lifecycle/planning/" class="sidebar-item-text sidebar-link">Planning</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/planning/ethics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Ethics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/planning/partners.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Partners</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/planning/funding.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Funding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/planning/piloting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Piloting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/planning/criticism.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Criticism</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/planning/preanalysis-plan.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Preanalysis Plan</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../lifecycle/realization/" class="sidebar-item-text sidebar-link">Realization</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/realization/pivoting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Pivoting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/realization/populated-pap.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Populated preanalysis plan</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/realization/reconciliation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Reconciliation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/realization/writing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Writing</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../lifecycle/integration/" class="sidebar-item-text sidebar-link">Integration</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/integration/communicating.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">Communicating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/integration/archiving.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Archiving</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/integration/reanalysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Reanalysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/integration/replication.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Replication</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/integration/meta-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Meta-analysis</span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../epilogue.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Epilogue</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p align="center">
<a style="color: black; text-decoration: none; font-size: 17px" target="_new" href="https://press.princeton.edu/books/paperback/9780691199573/research-design-in-the-social-sciences"> <img style="border: 1px solid darkgray; margin-bottom: 5px" width="100px" src="../figures/cover.jpg"><br>Preorder book</a>
</p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#elements-of-diagnoses" id="toc-elements-of-diagnoses" class="nav-link active" data-scroll-target="#elements-of-diagnoses"><span class="toc-section-number">10.1</span>  Elements of diagnoses</a>
  <ul class="collapse">
<li><a href="#diagnosand-statistics" id="toc-diagnosand-statistics" class="nav-link" data-scroll-target="#diagnosand-statistics"><span class="toc-section-number">10.1.1</span>  Diagnosand statistics</a></li>
  <li><a href="#diagnosands" id="toc-diagnosands" class="nav-link" data-scroll-target="#diagnosands"><span class="toc-section-number">10.1.2</span>  Diagnosands</a></li>
  </ul>
</li>
  <li><a href="#sec-ch10s2" id="toc-sec-ch10s2" class="nav-link" data-scroll-target="#sec-ch10s2"><span class="toc-section-number">10.2</span>  Types of diagnosands</a></li>
  <li>
<a href="#estimation-of-diagnosands" id="toc-estimation-of-diagnosands" class="nav-link" data-scroll-target="#estimation-of-diagnosands"><span class="toc-section-number">10.3</span>  Estimation of diagnosands</a>
  <ul class="collapse">
<li><a href="#analytic-design-diagnosis" id="toc-analytic-design-diagnosis" class="nav-link" data-scroll-target="#analytic-design-diagnosis"><span class="toc-section-number">10.3.1</span>  Analytic design diagnosis</a></li>
  <li><a href="#design-diagnosis-by-simulation" id="toc-design-diagnosis-by-simulation" class="nav-link" data-scroll-target="#design-diagnosis-by-simulation"><span class="toc-section-number">10.3.2</span>  Design diagnosis by simulation</a></li>
  <li><a href="#sec-ch10s3ss3" id="toc-sec-ch10s3ss3" class="nav-link" data-scroll-target="#sec-ch10s3ss3"><span class="toc-section-number">10.3.3</span>  Simulation error</a></li>
  </ul>
</li>
  <li>
<a href="#how-to-diagnose-designs" id="toc-how-to-diagnose-designs" class="nav-link" data-scroll-target="#how-to-diagnose-designs"><span class="toc-section-number">10.4</span>  How to diagnose designs</a>
  <ul class="collapse">
<li><a href="#sec-ch10s4ss1" id="toc-sec-ch10s4ss1" class="nav-link" data-scroll-target="#sec-ch10s4ss1"><span class="toc-section-number">10.4.1</span>  Exploring design tradeoffs</a></li>
  <li><a href="#sec-ch10s4ss2" id="toc-sec-ch10s4ss2" class="nav-link" data-scroll-target="#sec-ch10s4ss2"><span class="toc-section-number">10.4.2</span>  Diagnosis under model uncertainty</a></li>
  <li><a href="#adjudicating-between-competing-models" id="toc-adjudicating-between-competing-models" class="nav-link" data-scroll-target="#adjudicating-between-competing-models"><span class="toc-section-number">10.4.3</span>  Adjudicating between competing models</a></li>
  </ul>
</li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="toc-section-number">10.5</span>  Summary</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body" style="text-align: center">
        <img width="400px" src="https://draft.declaredesign.org/figures/cover.jpg" style="margin-bottom: 15px"><br>
        Available for preorder from Princeton University Press
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <!--<button type="button" class="btn btn-primary">Buy book</button>-->
        <a href="https://press.princeton.edu" target="_blank" class="btn btn-info" role="button">Preorder book</a>
      </div>
    </div>
  </div>
</div>

<header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-ch10" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diagnosing designs</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>Research design diagnosis is the process of evaluating the properties of a research design. We invent the term “diagnosand” to refer to those properties of a research design we would like to diagnose. Many diagnosands are familiar. Power is the probability of obtaining a statistically significant result. Bias is the average deviation of estimates from the estimand. Other diagnosands are more exotic, like the Type-S error rate, which is the probability the estimate has the incorrect sign, conditional on being statistically significant <span class="citation" data-cites="Gelman2014b">(<a href="../references.html#ref-Gelman2014b" role="doc-biblioref">Gelman and Carlin 2014</a>)</span>. This chapter focuses mainly on the use of Monte Carlo computer simulations to estimate diagnosands, though we touch on analytic design diagnosis as well.</p>
<p>Research designs are strong when the empirical answer <span class="math inline">\(a_{d^*}\)</span> generated by the design is close to the true answer <span class="math inline">\(a_{m^*}\)</span>. In general we cannot know <span class="math inline">\(a_{m^*}\)</span> with certainty—some combination of the fundamental problems of generalization, causal inference, and descriptive inference conspire to hide the truth from us. This problem means we have to assess the performance of our designs, not with respect to the real world, but instead with respect to our unverified and unverifiable beliefs about the world. In other words, we assess the properties of research designs by comparing the simulated answer <span class="math inline">\(a_d\)</span> to the answers under the model <span class="math inline">\(a_m\)</span>, over many possible realizations of the design.</p>
<p><a href="#fig-ch10num1">Figure&nbsp;<span>10.1</span></a> below is similar to <a href="declaring-designs.html#fig-ch2num1">Figure&nbsp;<span>5.1</span></a>, which we described when defining the components of a research design. To recapitulate the main points of that discussion: The theoretical half of a research design defines an inquiry <em>I</em> in terms of a model <em>M</em>. The true answer to that question is the inquiry applied to the real world <span class="math inline">\(I(m^*) = a_{m^*}\)</span>. The empirical half of a research design applies the data strategy to the real world to generate a dataset (<span class="math inline">\(D(m^*) = d^*\)</span>), then applies the answer strategy to the realized dataset to generate an answer: (<span class="math inline">\(A(d^*) = a_{d^*}\)</span>). All these stars reflect the fact that <em>reality</em> plays an important role in empirical research designs. We commit to the notion that there are <em>real</em> answers to the questions we have posed. Our empirical answers are tethered to reality because the data strategy generates information that depends on the real world.</p>
<p>When we simulate and diagnose designs, however, this tether to reality is snipped, and we find ourselves in the bottom half of <a href="#fig-ch10num1">Figure&nbsp;<span>10.1</span></a>. When we simulate, the theoretical half of the design entertains many possibilities in the model <em>M</em>, which we label <span class="math inline">\(m_1\)</span>, <span class="math inline">\(m_2\)</span>, …, <span class="math inline">\(m_k\)</span>. The answers under each of <span class="math inline">\(m_1\)</span>, <span class="math inline">\(m_2\)</span>, …, <span class="math inline">\(m_k\)</span> models are labeled <span class="math inline">\(a_{m_k}\)</span>. Each of the <span class="math inline">\(k\)</span> possibilities is generates a different answer to the inquiry: <span class="math inline">\(a_{m_1}\)</span>, <span class="math inline">\(a_{m_2}\)</span>, …, <span class="math inline">\(a_{m_k}\)</span>. Importantly, the simulated research design does not have access to the true answer <span class="math inline">\(a_{m^*}\)</span>, only answers under the <span class="math inline">\(k\)</span> considered models.</p>
<p>We pause to address one confusing aspect of our notation. The set of models <span class="math inline">\(m_1\)</span>, <span class="math inline">\(m_2\)</span>, …, <span class="math inline">\(m_k\)</span> could refer to a set of <span class="math inline">\(k\)</span> separate theoretical perspectives. Or it could refer to <span class="math inline">\(m_1\)</span>, <span class="math inline">\(m_2\)</span>, …, <span class="math inline">\(m_k\)</span> draws from the same basic model, but the values of the exogenous variables (following the specific meaning described in <a href="specifying-model.html#sec-ch6s1ss1"><span>Section&nbsp;6.1.1</span></a>) are slightly different. In other words, our notation doesn’t draw a deep distinction between large differences between theoretical models and small ones.</p>
<p>When we simulate, the empirical half of the design is similarly dissociated from reality. We apply the data strategy <span class="math inline">\(D\)</span> to each of the model draws <span class="math inline">\(m_k\)</span> to produce simulated datasets index as <span class="math inline">\(d_k\)</span>. These fabricated datasets may be similar to or different from the true dataset <span class="math inline">\(d^*\)</span> that would result if the design were realized (the more similar the better). We apply the answer strategy <em>A</em> to each simulated dataset <span class="math inline">\(d_k\)</span> in order to produce simulated answers <span class="math inline">\(a_{d_k}\)</span>.</p>
<p>A comparison of the top row to the bottom three rows of <a href="#fig-ch10num1">Figure&nbsp;<span>10.1</span></a> shows how actual research designs differ from simulated research designs. Actual research designs are influenced by reality—we learn about the real world by conducting empirical research. We don’t learn about the real world from simulated research designs. Instead, we learn about research designs themselves. We learn how the research design would behave <em>if</em> the real world <span class="math inline">\(m^*\)</span> were like the model draw <span class="math inline">\(m_1\)</span>—or like <span class="math inline">\(m_{100}\)</span>. We can only evaluate designs under the possibilities we consider in <span class="math inline">\(M\)</span>. If the world <span class="math inline">\(m^*\)</span> is not in that set of possibilities, we won’t have evaluated the design under the most important setting, i.e., what will happen when we actually apply the design in reality. We want to follow <a href="../introduction/research-design-principles.html#exm-designagnostically">Principle&nbsp;<span>3.2</span></a> to “design agnostically” or in order words, to consider such a wide range of possibilities that some <span class="math inline">\(a_{m_k}\)</span> will be close enough to <span class="math inline">\(a_{m^*}\)</span>.</p>
<div id="fig-ch10num1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="../figures/figure-10-1.svg" class="lightbox" title="Simulations in the MIDA framework" data-gallery="quarto-lightbox-gallery-1"><img src="../figures/figure-10-1.svg" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;10.1: Simulations in the <em>MIDA</em> framework</figcaption><p></p>
</figure>
</div>
<p>With this definition of a diagnosis in hand, we can now sharpen our thinking on when we have a complete design declaration. A design declaration is “diagnosand-complete” when the declaration contains enough information to calculate a specific diagnosand, or statistic about the design. The “bias” diagnosand requires that all four of <em>M</em>, <em>I</em>, <em>D</em>, and <em>A</em> are specified in sufficient detail because we need to be able to compare the answer under the model (<span class="math inline">\(a_m\)</span>) to the simulated empirical answer (<span class="math inline">\(a_d\)</span>). The “statistical power” diagnosand often does not require the inquiry <span class="math inline">\(I\)</span> to be specified, since we can mechanistically conduct null hypothesis significance tests without reference to inquiries. Neither the “bias” nor “statistical power” diagnosands require any details of confidence interval construction, but without those details, the declaration is not diagnosand-complete for “coverage.”</p>
<p>Every design we have ever declared is diagnosand-complete for some diagnosands but not for others. Diagnosand-completeness for every common diagnosand is not a goal for design declaration. We want to be diagnosand-complete for the set of diagnosands that matter most in a particular research setting.</p>
<section id="elements-of-diagnoses" class="level2" data-number="10.1"><h2 data-number="10.1" class="anchored" data-anchor-id="elements-of-diagnoses">
<span class="header-section-number">10.1</span> Elements of diagnoses</h2>
<section id="diagnosand-statistics" class="level3" data-number="10.1.1"><h3 data-number="10.1.1" class="anchored" data-anchor-id="diagnosand-statistics">
<span class="header-section-number">10.1.1</span> Diagnosand statistics</h3>
<p>Diagnosands are summaries of the distributions of diagnostic statistics. We’ll start by defining diagnostic statistics, then move on to describing how to generate the distribution of diagnostic statistics, then how to summarize those distributions in order to estimate diagnosands.</p>
<p>A diagnostic statistic <span class="math inline">\(\phi_k\)</span> is itself a function of <span class="math inline">\(a_{m_k}\)</span> and <span class="math inline">\(a_{d_k}\)</span>: <span class="math inline">\(\phi_k = g(a_{m_k}, a_{d_k})\)</span>. We elide here two important notational annoyances. For the purpose of the following discussion of diagnostic statistics and diagnosands, <span class="math inline">\(a_{d_k}\)</span> can refer to a estimate like an difference-in-means estimate or an associated uncertainty statistic like a standard error or a <span class="math inline">\(p\)</span>-value. Importantly, diagnostic statistics can be functions that depend on <span class="math inline">\(a_{m_k}\)</span> only, <span class="math inline">\(a_{d_k}\)</span> only, or both together.</p>
<p>Each diagnostic statistic is the result of a different function <span class="math inline">\(g\)</span>. For example, the “error” diagnostic statistic is produced by this function: <span class="math inline">\(g(a_{m_k}, a_{d_k}) = a_{d_k} - a_{m_k}\)</span>. The “significant” diagnostic statistic is <span class="math inline">\(g(a_{d_k}) = \mathbf{I}[p(a_{d_k}) \leq \alpha]\)</span>, where <span class="math inline">\(p()\)</span> is a function of the empirical answer that returns a <span class="math inline">\(p\)</span>-value, <span class="math inline">\(\alpha\)</span> is a significance cutoff, and <span class="math inline">\(\mathbf{I}\)</span> is an indicator function that returns 1 when the <span class="math inline">\(p\)</span>-value is below the cutoff and <span class="math inline">\(0\)</span> when it is above. A diagnostic statistic is something that can be calculated on the basis of a single run of the design.</p>
<p>Typically, diagnostic statistics will be different from simulation to simulation In other words, <span class="math inline">\(\phi_1\)</span> will be different from <span class="math inline">\(\phi_2\)</span>, <span class="math inline">\(\phi_2\)</span> will be different from <span class="math inline">\(\phi_3\)</span>, and so on. These differences arise partially from the variation in <em>M</em>: <span class="math inline">\(m_1\)</span> is different from <span class="math inline">\(m_2\)</span>, <span class="math inline">\(m_2\)</span> is different from <span class="math inline">\(m_3\)</span>, and so on. Differences can also arise from the explicitly random procedures in <span class="math inline">\(D\)</span>: sampling, assignment, and measurement can all include stochastic elements that will ramify through to the diagnostic statistics. As a result of these sources of variation, a diagnostic statistic is a random variable <span class="math inline">\(\Phi\)</span>.</p>
</section><section id="diagnosands" class="level3" data-number="10.1.2"><h3 data-number="10.1.2" class="anchored" data-anchor-id="diagnosands">
<span class="header-section-number">10.1.2</span> Diagnosands</h3>
<p>A diagnosand is a summary of the distribution of <span class="math inline">\(\Phi\)</span>, written <span class="math inline">\(f(\Phi)\)</span>. For example, the expectation function <span class="math inline">\(\E[\Phi]\)</span> reports the expectation (the mean) of <span class="math inline">\(\Phi\)</span>.</p>
<p>Let’s back up a moment to work through two concrete examples of common diagnosands: bias and power (see <a href="#sec-ch10s2"><span>Section&nbsp;10.2</span></a> for a more exhaustive list).</p>
<p>Consider the diagnosand “bias” in the context of a two-arm randomized trial where the inquiry is the average treatment effect, the data strategy entails complete random assignment, and the answer strategy is the difference-in-means. Bias is the average difference between the estimand and the estimate. Under a single realization <span class="math inline">\(m_k\)</span> of the model <em>M</em>, the value of the ATE will be a particular number, which we call <span class="math inline">\(a_{m_k}\)</span>. We simulate a random assignment and measurement of observed outcomes, then apply the difference-in-means estimator. The diagnostic statistic is the error <span class="math inline">\(a_{d_k} - a_{m_k}\)</span>; this error is a random variable because each <span class="math inline">\(m_k\)</span> differs slightly. The bias diagnosand is the expectation of this random variable is <span class="math inline">\(\E[a_{d_k} - a_{m_k}]\)</span>, where the expectation is taken over the randomization distribution implied by <em>M</em> and <em>D</em> (or distinct regions of the randomization distribution).</p>
<p>Now consider the diagnosand “power.” Like bias, statistical power is an expectation, this time of the “significant” diagnostic statistic <span class="math inline">\(\mathbf{I}(p(a_{d_k}) \leq 0.05)\)</span>. Power describes how frequently the answer strategy will return a statistically significant result. Some textbooks define statistical power as one minus the Type II error rate, where a Type II error is the failure to reject the null hypothesis, given that the null hypothesis is false. This definition is accurate, but hard to understand. The phrase “given that the null hypothesis is false” refers to model possibilities (<span class="math inline">\(a_{m_k}\)</span>’s) in which the null hypothesis does not hold. Our definition of power is instead, “the probability of getting a statistically significant result, conditional on a set of beliefs about the model.”</p>
<p>Uncertainty statistics like standard errors can be thought of as empirical estimates of diagnosands describing the quality of your design under some set of models.</p>
<p>Suppose we report that the estimate is equal to 15 and carries with it a standard error of 6. Here we are communicating that we now think our design has the property that, if we were to run it over and over, the standard deviation of our estimates would be 6. That is, if we were to declare a design over a large class of models that all have the same outcome variance and combined it with <em>I</em>, <em>D</em>, and <em>A</em>, and diagnosed, the standard deviation of the estimates under all those models would be 6.</p>
<p>Likewise, estimated <span class="math inline">\(p\)</span>-values can also be thought of as estimates of a peculiar diagnosand: the probability of obtaining a test statistic of a particular value, under a maintained null model. That is, if we were to write down a null model <span class="math inline">\(m_{0}\)</span> under which the estimand were in fact zero, then combined it with <em>I</em>, <em>D</em>, and <em>A</em>, we could diagnose that design to learn the fraction of estimates that are as large or larger than 15—a <span class="math inline">\(p\)</span>-value.</p>
<p>Thinking about <span class="math inline">\(p\)</span>-values as diagnosands can be seen most directly in the randomization inference approach to hypothesis testing. Randomization inference often considers “sharp” null hypothesis in which we impute the missing potential outcomes with exactly their observed values, then simulate all the ways the design could come out holding <em>I</em>, <em>D</em>, and <em>A</em> constant. The <span class="math inline">\(p\)</span>-value is the fraction of simulations in which the null model generates estimates that are more extreme than the observed estimate. See <a href="choosing-answer-strategy.html#sec-ch9s3ss5"><span>Section&nbsp;9.3.5</span></a> for a worked example of this approach.</p>
<p>Even frequentist confidence intervals, with their notoriously confusing interpretation (a 95% confidence interval is an interval that has the goal of covering the estimand 95% of the time) can be viewed as estimates of the 2.5th and 97.5th quantiles of the sampling distribution under the model that the estimand equals the estimate.</p>
<p>The payoff from thinking about uncertainty statistics as estimates of diagnosands is that uncertainty statistics can be <strong>poor</strong> estimators of diagnosands. For example, social scientists criticize one another’s choice of standard error—classical or robust, clustered or not, bootstrapped, jackknifed, and on and on. The reason for this debate is that when the procedures we follow to form uncertainty statistics are inappropriate for the design setting, we can be falsely confident in our answers.</p>
<p><a href="#fig-ch10num2">Figure&nbsp;<span>10.2</span></a> illustrates what’s at stake in the age old contest between classical standard errors and robust standard errors. Here we are in the context of a two arm trial under three settings: the control potential outcomes are higher variance, the groups have the same variances, or the treated outcomes have higher variance. The calculation for classical standard errors pools the data from both groups when estimating a variance, thereby assuming “homoskedasticity,” a Greek work for having the “same spread.” This estimation choice leads to poor performance. Depending on the fraction of the sample that receive treatment, the estimate of the sampling distribution can be upwardly biased (conservative) or downwardly biased (anti-conservative or falsely confident). We’re usually worried about standard error estimates being too small because anti-conservatism is probably worse for scientific communication than conservatism.</p>
<p>Robust standard errors are “heteroskedasticity-robust,” which means that that the estimation does not assume that the two groups have the same error variance. <span class="citation" data-cites="samii2012equivalencies">Samii and Aronow (<a href="../references.html#ref-samii2012equivalencies" role="doc-biblioref">2012</a>)</span> show that a particular variant of robust standard errors (HC2) is exactly equal to the Neyman variance estimator described in <a href="redesigning.html#sec-ch10s3ss1"><span>Section&nbsp;11.3.1</span></a>, which is why HC2 robust standard errors are default in the <code>lm_robust</code> function. The bottom row of <a href="#fig-ch10num2">Figure&nbsp;<span>10.2</span></a> shows that the robust standard error estimator hews closely to the true value of the diagnosand in all of the design settings considered. We prefer robust SEs because they do impose extra model assumptions like homoskedasticity that are not grounded in any particular design feature.</p>
<div id="fig-ch10num2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="../figures/figure-10-2.svg" class="lightbox" title="Why robust standard errors are preferred to classical standard errors" data-gallery="quarto-lightbox-gallery-2"><img src="../figures/figure-10-2.svg" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;10.2: Why robust standard errors are preferred to classical standard errors</figcaption><p></p>
</figure>
</div>
</section></section><section id="sec-ch10s2" class="level2" data-number="10.2"><h2 data-number="10.2" class="anchored" data-anchor-id="sec-ch10s2">
<span class="header-section-number">10.2</span> Types of diagnosands</h2>
<p>As described above, a diagnostic statistic is any summary function of <span class="math inline">\(a_m\)</span> and <span class="math inline">\(a_d\)</span>, and a diagnosand is any summary of the distribution of diagnostic statistics. As a result, there are a great many diagnosands researchers may consider. In <a href="#tbl-diagnosticstatistics">Table&nbsp;<span>10.1</span></a>, we introduce a nonexhaustive set of diagnostic statistics, and in <a href="#tbl-diagnosands">Table&nbsp;<span>10.2</span></a> a nonexhaustive set of diagnosands.</p>
<div id="tbl-diagnosticstatistics" class="anchored">
<table class="table">
<caption>Table&nbsp;10.1: Examples of diagnostic statistics.</caption>
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead><tr class="header">
<th>Diagnostic statistic</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Estimate</td>
<td><span class="math inline">\(a_{d_k}\)</span></td>
</tr>
<tr class="even">
<td>Estimand under the model</td>
<td><span class="math inline">\(a_{m_k}\)</span></td>
</tr>
<tr class="odd">
<td>
<span class="math inline">\(p\)</span>-value</td>
<td><span class="math inline">\(p(a_{d_k})\)</span></td>
</tr>
<tr class="even">
<td>
<span class="math inline">\(p\)</span>-value is no greater than <span class="math inline">\(\alpha\)</span>
</td>
<td><span class="math inline">\(\mathbf{I}(p \leq \alpha)\)</span></td>
</tr>
<tr class="odd">
<td>Confidence interval</td>
<td><span class="math inline">\(\mathrm{CI}_{1-\alpha}\)</span></td>
</tr>
<tr class="even">
<td>Confidence interval covers the estimand under the model</td>
<td><span class="math inline">\(\mathrm{covers}_{a_m} \equiv \mathbb{I}\{ a_m \in \mathrm{CI}_{1-\alpha} \}\)</span></td>
</tr>
<tr class="odd">
<td>Estimated standard error</td>
<td><span class="math inline">\(\widehat\sigma(A)\)</span></td>
</tr>
<tr class="even">
<td>Cost</td>
<td><span class="math inline">\(\mathrm{cost}\)</span></td>
</tr>
<tr class="odd">
<td>Proportion of subjects harmed</td>
<td><span class="math inline">\(\Pr(\mathrm{harm}) \equiv \frac{1}{n} \sum_i \mathrm{harm_i}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-diagnosands" class="anchored">
<table class="table">
<caption>Table&nbsp;10.2: Examples of iagnosands.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 54%">
<col style="width: 29%">
</colgroup>
<thead><tr class="header">
<th>Diagnosand</th>
<th>Description</th>
<th>Definition</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Average estimate</td>
<td></td>
<td><span class="math inline">\(\E(a_d)\)</span></td>
</tr>
<tr class="even">
<td>Average estimand</td>
<td></td>
<td><span class="math inline">\(\E(a_m)\)</span></td>
</tr>
<tr class="odd">
<td>Power</td>
<td>Probability of rejecting null hypothesis of no effect</td>
<td><span class="math inline">\(\E(I(p \leq \alpha))\)</span></td>
</tr>
<tr class="even">
<td>Null risk</td>
<td>Probability of failing to reject null hypothesis of no effect</td>
<td><span class="math inline">\(\E(I(p &gt; \alpha))\)</span></td>
</tr>
<tr class="odd">
<td>Bias</td>
<td>Expected difference between estimate and estimand</td>
<td><span class="math inline">\(\E(a_d - a_m)\)</span></td>
</tr>
<tr class="even">
<td>Variance of the estimates</td>
<td></td>
<td><span class="math inline">\(\V(a_d)\)</span></td>
</tr>
<tr class="odd">
<td>True standard error</td>
<td></td>
<td><span class="math inline">\(\sqrt{\V(a_d)}\)</span></td>
</tr>
<tr class="even">
<td>Average estimated standard error</td>
<td></td>
<td><span class="math inline">\(\widehat\sigma(A)\)</span></td>
</tr>
<tr class="odd">
<td>Root mean-squared-error (RMSE)</td>
<td></td>
<td><span class="math inline">\(\sqrt{\E(a_d - a_m)}\)</span></td>
</tr>
<tr class="even">
<td>Coverage</td>
<td>Probability confidence interval overlaps estimand</td>
<td><span class="math inline">\(\Pr(\mathrm{covers}_{a_m})\)</span></td>
</tr>
<tr class="odd">
<td>Bias‐eliminated coverage</td>
<td>Probability confidence interval overlaps average estimate (<span class="citation" data-cites="morrisetal2019">Morris, White, and Crowther (<a href="../references.html#ref-morrisetal2019" role="doc-biblioref">2021</a>)</span>)</td>
<td><span class="math inline">\(\Pr(\mathrm{covers}_{a_d})\)</span></td>
</tr>
<tr class="even">
<td>Type-S error rate</td>
<td>Probability estimate has an incorrect sign, if statistically significant <span class="citation" data-cites="Gelman2014b">(<a href="../references.html#ref-Gelman2014b" role="doc-biblioref">Gelman and Carlin 2014</a>)</span>
</td>
<td><span class="math inline">\(\Pr(\mathrm{sgn}(a_d) \neq \mathrm{sgn}(a_m) \mid p \leq \alpha)\)</span></td>
</tr>
<tr class="odd">
<td>Exaggeration ratio</td>
<td>Expected ratio of absolute value of estimate to estimand, if statistically significant <span class="citation" data-cites="Gelman2014b">(<a href="../references.html#ref-Gelman2014b" role="doc-biblioref">Gelman and Carlin 2014</a>)</span>
</td>
<td><span class="math inline">\(\E( a_d / a_m \mid p \leq \alpha)\)</span></td>
</tr>
<tr class="even">
<td>Type I error</td>
<td>Rejecting the null hypothesis when it is true</td>
<td><span class="math inline">\(\Pr(p \leq \alpha \mid a_m = a^0)\)</span></td>
</tr>
<tr class="odd">
<td>Type II error</td>
<td>Failure to reject the null hypothesis when it is false</td>
<td><span class="math inline">\(\Pr(p \geq \alpha \mid a_m \neq a^0)\)</span></td>
</tr>
<tr class="even">
<td>Sampling bias</td>
<td>Expected difference between population average treatment effect and sample average treatment effect <span class="citation" data-cites="imai2008essential">(<a href="../references.html#ref-imai2008essential" role="doc-biblioref">Imai, King, and Stuart 2008</a>)</span>
</td>
<td><span class="math inline">\(\E(a_{m_{\mathrm{sample}}} - a_{m_{\mathrm{population}}})\)</span></td>
</tr>
<tr class="odd">
<td>Expected maximum cost</td>
<td>Maximum cost across possible realizations of the study</td>
<td><span class="math inline">\(\max{\mathrm{cost}}\)</span></td>
</tr>
<tr class="even">
<td>Bayesian learning</td>
<td>Difference between prior and posterior guess of the value of the estimand</td>
<td><span class="math inline">\(a_{m_{\mathrm{post}}} - a_{m_{\mathrm{pre}}}\)</span></td>
</tr>
<tr class="odd">
<td>Value for money</td>
<td>Probability that a decision based on estimated effect yields net benefits</td>
<td></td>
</tr>
<tr class="even">
<td>Success</td>
<td>Qualitative assessment of the success of a study</td>
<td></td>
</tr>
<tr class="odd">
<td>Minimum detectable effect (MDE)</td>
<td>Smallest effect size for which the power of the design is nominal (e.g., powered at 80%)</td>
<td><span class="math inline">\(\mathrm{argmin}_{a_{m_*}} \Pr(p \leq \alpha) = 0.8\)</span></td>
</tr>
<tr class="even">
<td>Robustness</td>
<td>Joint probability of rejecting the null hypothesis across multiple tests</td>
<td></td>
</tr>
<tr class="odd">
<td>Maximum proportion of subjects harmed</td>
<td></td>
<td><span class="math inline">\(\max{\Pr(\mathrm{harm})}\)</span></td>
</tr>
</tbody>
</table>
</div>
</section><section id="estimation-of-diagnosands" class="level2" data-number="10.3"><h2 data-number="10.3" class="anchored" data-anchor-id="estimation-of-diagnosands">
<span class="header-section-number">10.3</span> Estimation of diagnosands</h2>
<section id="analytic-design-diagnosis" class="level3" data-number="10.3.1"><h3 data-number="10.3.1" class="anchored" data-anchor-id="analytic-design-diagnosis">
<span class="header-section-number">10.3.1</span> Analytic design diagnosis</h3>
<p>Diagnosis can be done with analytic, pencil-and-paper methods. In an analytic design diagnosis, we typically derive a formula that returns the value of a diagnosand under a stipulated set of beliefs about the model, inquiry, data strategy, and answer strategy. For example, research design textbooks often contain analytic design diagnoses for statistical power. <span class="citation" data-cites="Gerber2012">Gerber and Green (<a href="../references.html#ref-Gerber2012" role="doc-biblioref">2012</a>)</span> write:</p>
<blockquote class="blockquote">
<p>“To illustrate a power analysis, consider a completely randomized experiment where <span class="math inline">\(N&gt;2\)</span> of <span class="math inline">\(N\)</span> units are selected into a binary treatment. The researcher must now make assumptions about the distributions of outcomes for treatment and for control units. In this example, the researcher assumes that the control group has a normally distributed outcome with mean <span class="math inline">\(\mu_c\)</span>, the treatment group has a normally distributed outcome with mean <span class="math inline">\(\mu_t\)</span>, and both group’s outcomes have a standard deviation <span class="math inline">\(\sigma\)</span>. The researcher must also choose <span class="math inline">\(\alpha\)</span>, the desired level of statistical significance (typically 0.05). Under this scenario, there exists a simple asymptotic approximation for the power of the experiment (assuming that the significance test is two-tailed): <span class="math display">\[
\beta = \Phi \bigg(\frac{|\mu_t - \mu_c| \sqrt{N}}{2\sigma} - \Phi^{-1} \left(1 - \frac{\alpha}{2}\right) \bigg)
\]</span> where <span class="math inline">\(\beta\)</span> is the statistical power of the experiment, <span class="math inline">\(\Phi(\cdot)\)</span> is the normal cumulative distribution function (CDF), and <span class="math inline">\(\Phi^{-1}(\cdot)\)</span> is the inverse of the normal CDF.”</p>
</blockquote>
<p>This power formula makes <strong>detailed</strong> assumptions about <em>M</em>, <em>I</em>, <em>D</em>, and <em>A</em>. Under <em>M</em>, it assumes that both potential outcomes are normally distributed with group specific means and a common variance. Under <em>I</em>, it assumes the average treatment effect. Under <em>D</em>, it assumes a particular randomization strategy (simple random assignment). Under <em>A</em>, it assumes a particular hypothesis testing approach (equal variance <span class="math inline">\(t\)</span>-test with <span class="math inline">\(N - 2\)</span> degrees of freedom). Whether this set of assumptions is “close enough” will depend on the research setting.</p>
<p>Analytic design diagnosis can be hugely useful, since they cover a large families of designs that meet the scope criteria. For example, the “standard error” diagnosand <span class="math inline">\(\sqrt{\E[(a_{d_k} - \E[a_{d_k}])^2]}\)</span> of a standard two-arm trial has been worked out by statisticians to be <span class="math inline">\(\sqrt{\frac{1}{n-1}\left\{\frac{m\V(Y_i(0))}{n-m} + \frac{(N-m)\V(Y_i(1))}{m} + 2Cov(Y_i(0), Y_i(1))\right\}}\)</span> (see <a href="redesigning.html#sec-ch10s3ss1"><span>Section&nbsp;11.3.1</span></a> for details). This standard error is accurate for any completely randomized design with stable potential outcomes and a difference-in-means estimator. Many, if not most, advances in our understanding of the properties of research design come from analytic design diagnosis. For example, <span class="citation" data-cites="middleton2008bias">Middleton (<a href="../references.html#ref-middleton2008bias" role="doc-biblioref">2008</a>)</span> and <span class="citation" data-cites="imai2009essential">Imai, King, and Nall (<a href="../references.html#ref-imai2009essential" role="doc-biblioref">2009</a>)</span> show that cluster randomized trials with heterogeneous cluster sizes are not unbiased for the ATE, which leads to the design recommendation that clustered trials should block on cluster size. These lessons apply broadly, more broadly perhaps than the lessons learned about a specific design in a specific Monte Carlo simulation.</p>
<p>That said, scholars conducting analytic design diagnosis have only worked out a few diagnosands for a limited set of designs. Since designs are so heterogeneous and can vary on so many dimensions, computer simulation is often the only feasible way to diagnose. We learn a lot from analytic design diagnosis—what are the important parameters to consider, what are the important inferential problems—but they often cannot provide direct answers to practical questions like, how many subjects do I need for my conjoint experiment? For that reason, we turn to design diagnosis via Monte Carlo simulation.</p>
</section><section id="design-diagnosis-by-simulation" class="level3" data-number="10.3.2"><h3 data-number="10.3.2" class="anchored" data-anchor-id="design-diagnosis-by-simulation">
<span class="header-section-number">10.3.2</span> Design diagnosis by simulation</h3>
<p>Research design diagnosis by simulation occurs in two steps. First we simulate research designs repeatedly, collecting diagnostic statistics from each run of the simulation. Second, we summarize the distribution of the diagnostic statistics in order to estimate the diagnosands.</p>
<p>Monte Carlo simulations of research designs can be written in any programming language. To illustrate the most common way of simulating a design—a for loop—we’ll write a concise simulation in base R code. <a href="#lem-ch10num1">Diagnosis&nbsp;<span>10.1</span></a> conducts the simulation 500 times, each time, collecting the <span class="math inline">\(p\)</span>-value associated with a regression estimate of the average effect of an outcome on a treatment.</p>
<p>Loops like this one can be implemented in any language and they remain a good tool for design diagnosis. We think, however, writing simulations in this way obscures what parts of the design refer to the model, the inquiry, the data strategy, or the answer strategy. We might imagine <code>Z</code> and <code>Y</code> are generated by a data strategy that randomly assigns Z, then measures Y (though without a language for linking code to design steps, it’s a bit unclear). The answer strategy involves running a regression of <code>Y</code> on <code>Z</code>, then conducting a hypothesis test against the null hypothesis that the coefficient on Z is 0. The model and inquiry are left entirely implicit. The inquiry might be the ATE, but it might also be a question of whether the ATE is equal to zero. The model might include only two potential outcomes for each subject, or it might have more, we don’t know.</p>
<div id="lem-ch10num1" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 10.1 </strong></span>By-hand diagnosis example</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sims</span> <span class="op">&lt;-</span> <span class="fl">500</span></span>
<span><span class="va">p.values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="cn">NA</span>, <span class="va">sims</span><span class="op">)</span></span>
<span></span>
<span><span class="kw">for</span><span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">sims</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">Z</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="fl">100</span>, <span class="fl">1</span>, <span class="fl">0.5</span><span class="op">)</span></span>
<span>  <span class="va">U</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">100</span><span class="op">)</span></span>
<span>  <span class="va">Y</span> <span class="op">&lt;-</span> <span class="fl">0.2</span> <span class="op">*</span> <span class="va">Z</span> <span class="op">+</span> <span class="va">U</span></span>
<span>  <span class="va">p.values</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">Z</span><span class="op">)</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span><span class="op">[</span><span class="fl">2</span>, <span class="fl">4</span><span class="op">]</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">power</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">p.values</span> <span class="op">&lt;=</span> <span class="fl">0.05</span><span class="op">)</span></span>
<span><span class="va">power</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-forloop" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;10.3:  By-hand design diagnosis with a for-loop </caption>
 <thead><tr>
<th style="text-align:center;"> power </th>
  </tr></thead>
<tbody><tr>
<td style="text-align:center;"> 0.16 </td>
  </tr></tbody>
</table>
</div>
</div>
</div>
</div>
<p>For this reason, we advocate for explicit description of all four research design components. Explicit design declaration can <em>also</em> occur in any programming language, but DeclareDesign is purpose-built for this task. We begin with the explicit declaration of the same two-arm trial as above. We have 100 subjects with a constant response to treatment of 0.2 units. Our inquiry is the average difference between the treated and untreated potential outcomes—the ATE. We assign treatment using complete random assignment and estimate treatment effects using difference-in-means.</p>
<div id="def-ch10num1" class="declaration theorem definition">
<p><span class="theorem-title"><strong>Declaration 10.1 </strong></span>Example of declaration using DeclareDesign</p>
<div class="cell" data-file="scripts_declarations/declaration_10.1.R">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">declaration_10.1</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">declare_model</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="fl">100</span>,</span>
<span>    U <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,</span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span>  <span class="fl">0.2</span> <span class="op">*</span> <span class="va">Z</span> <span class="op">+</span> <span class="va">U</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span>ATE <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Y_Z_1</span> <span class="op">-</span> <span class="va">Y_Z_0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_assignment</span><span class="op">(</span>Z <span class="op">=</span> <span class="fu">complete_ra</span><span class="op">(</span><span class="va">N</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_measurement</span><span class="op">(</span>Y <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">Z</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">Z</span>, inquiry <span class="op">=</span> <span class="st">"ATE"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="lem-ch10num2" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 10.2 </strong></span>Diagnosis in DeclareDesign</p>
<p>We can now diagnose the declared design. For comparison with the loop, we calculate just one diagnosand: statistical power. Both approaches return approximately the same answer. Any difference between the two can be attributed to simulation error, which is why DeclareDesign by default returns a bootstrapped standard error for each diagnosand estimate. If we were to increase the number of simulations for both approaches dramatically (100,000 simulations would be plenty), the differences would vanish.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">diagnosands</span> <span class="op">&lt;-</span> <span class="fu">declare_diagnosands</span><span class="op">(</span>power <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">p.value</span> <span class="op">&lt;=</span> <span class="fl">0.05</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">diagnosis</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">diagnose_design</span><span class="op">(</span><span class="va">declaration_10.1</span>, </span>
<span>                  diagnosands <span class="op">=</span> <span class="va">diagnosands</span><span class="op">)</span></span>
<span></span>
<span><span class="va">diagnosis</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-diagnsissimplydd" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;10.4:  Design diagnosis using DeclareDesign </caption>
 <thead><tr>
<th style="text-align:center;"> power </th>
   <th style="text-align:center;"> se(power) </th>
   <th style="text-align:center;"> n_sims </th>
  </tr></thead>
<tbody><tr>
<td style="text-align:center;"> 0.1615 </td>
   <td style="text-align:center;"> 0.0083482 </td>
   <td style="text-align:center;"> 2000 </td>
  </tr></tbody>
</table>
</div>
</div>
</div>
</div>
<p>Backing up, we now construct that same diagnosis step-by-step. We build up from a single simulation run of the design to the distribution of simulations, to summaries of that distribution.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">343</span><span class="op">)</span></span>
<span></span>
<span><span class="va">simulation_10.1</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">simulate_design</span><span class="op">(</span><span class="va">declaration_10.1</span>, sims <span class="op">=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>significant <span class="op">=</span> <span class="va">p.value</span> <span class="op">&lt;=</span> <span class="fl">0.05</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<p>We can run this simulation a single time with <code>run_design</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">run_design</span><span class="op">(</span><span class="va">declaration_10.1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-onesimulationdraw" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;10.5:  One simulation draw </caption>
 <thead><tr>
<th style="text-align:center;"> estimand </th>
   <th style="text-align:center;"> estimate </th>
   <th style="text-align:center;"> std.error </th>
   <th style="text-align:center;"> df </th>
   <th style="text-align:center;"> p.value </th>
   <th style="text-align:center;"> conf.low </th>
   <th style="text-align:center;"> conf.high </th>
  </tr></thead>
<tbody><tr>
<td style="text-align:center;"> 0.2 </td>
   <td style="text-align:center;"> 0.278 </td>
   <td style="text-align:center;"> 0.209 </td>
   <td style="text-align:center;"> 98 </td>
   <td style="text-align:center;"> 0.186 </td>
   <td style="text-align:center;"> -0.136 </td>
   <td style="text-align:center;"> 0.692 </td>
  </tr></tbody>
</table>
</div>
</div>
</div>
<p><a href="#fig-ch10num3">Figure&nbsp;<span>10.3</span></a> shows the information we might obtain from a single run of the simulation. The filled point is the estimate <span class="math inline">\(a_{d_k}\)</span>. The open triangle is the estimand <span class="math inline">\(a_{m_k}\)</span>. The bell-shaped curve is our normal-approximation based estimate of the sampling distribution. The standard deviation of this estimated distribution is our estimated standard error, which expresses our uncertainty. The confidence interval around the estimate is another expression of our uncertainty: We’re not sure where <span class="math inline">\(a_{d_k}\)</span> is, but if things are going according to plan, confidence intervals constructed this way will bracket <span class="math inline">\(a_{m_k}\)</span> 95% of the time.</p>
<div id="fig-ch10num3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="../figures/figure-10-3.svg" class="lightbox" title="Visualization of one draw from a design diagnosis." data-gallery="quarto-lightbox-gallery-3"><img src="../figures/figure-10-3.svg" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;10.3: Visualization of one draw from a design diagnosis.</figcaption><p></p>
</figure>
</div>
<p>From this single draw, we can’t yet estimate diagnosands, but we can calculate diagnostic statistics. The estimate was higher than the estimand in this draw, so the error is 0.45 - 0.20 = 0.25. Likewise, the squared error is (0.45 - 0.20)<span class="math inline">\(^2\)</span> = 0.0625. The <span class="math inline">\(p\)</span>-value is 0.01, which is well below the threshold of 0.05, so the “statistical significance” diagnostic statistic is equal to <code>TRUE</code>. The confidence interval stretches from 0.11 to 0.79, and since the value of the estimand (0.20) is between those bounds, the “covers” diagnostic statistic is equal to <code>TRUE</code> as well.</p>
<p>To calculate the distributions of the diagnostic statistics, we have to simulate designs not just once, but many times over. The bias diagnosand is the average error over many runs of the simulation. The statistical power diagnosand is the fraction of runs in which the estimate is significant. The coverage diagnosand is the frequency with which the confidence interval covers the estimand.</p>
<p><a href="#fig-ch10num4">Figure&nbsp;<span>10.4</span></a> visualizes 10 runs of the simulation. We can see that some of the draws produce statistically significant estimates (the shaded areas are small and the confidence intervals don’t overlap zero), but not all. We get a sense of the <em>true</em> standard error by seeing how the point estimates bounce around. We get a feel for the difference between the estimates of the standard error and true standard error. Design diagnosis is the process of learning about many ways the study might come out, not just the one way that it will.</p>
<div id="fig-ch10num4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="../figures/figure-10-4.svg" class="lightbox" title="Visualization of ten draws from a design diagnosis." data-gallery="quarto-lightbox-gallery-4"><img src="../figures/figure-10-4.svg" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;10.4: Visualization of ten draws from a design diagnosis.</figcaption><p></p>
</figure>
</div>
<p>This line of code does it all in one. We simulate the design (500 times by default) to calculate the diagnostic statistics, then we summarize them in terms of bias, the true standard error, RMSE, power, and coverage.</p>
<div id="lem-ch10num2" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 10.3 </strong></span>Design diagnosis in one step</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">diagnosis_10.3</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">diagnose_design</span><span class="op">(</span></span>
<span>    <span class="va">declaration_10.1</span>,</span>
<span>    diagnosands <span class="op">=</span> <span class="fu">declare_diagnosands</span><span class="op">(</span></span>
<span>      bias <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">estimate</span> <span class="op">-</span> <span class="va">estimand</span><span class="op">)</span>,</span>
<span>      true_se <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">estimate</span><span class="op">)</span>,</span>
<span>      power <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">p.value</span> <span class="op">&lt;=</span> <span class="fl">0.05</span><span class="op">)</span>,</span>
<span>      coverage <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">estimand</span> <span class="op">&lt;=</span> <span class="va">conf.high</span> <span class="op">&amp;</span></span>
<span>                        <span class="va">estimand</span> <span class="op">&gt;=</span> <span class="va">conf.low</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-estimateddiagnosands" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;10.6:  Diagnosand estimates with bootstrapped standard errors in parentheses </caption>
 <thead><tr>
<th style="text-align:center;"> bias </th>
   <th style="text-align:center;"> true se </th>
   <th style="text-align:center;"> power </th>
   <th style="text-align:center;"> coverage </th>
  </tr></thead>
<tbody><tr>
<td style="text-align:center;"> -0.00 (0.00) </td>
   <td style="text-align:center;"> 0.20 (0.00) </td>
   <td style="text-align:center;"> 0.17 (0.01) </td>
   <td style="text-align:center;"> 0.96 (0.00) </td>
  </tr></tbody>
</table>
</div>
</div>
</div>
</div>
</section><section id="sec-ch10s3ss3" class="level3" data-number="10.3.3"><h3 data-number="10.3.3" class="anchored" data-anchor-id="sec-ch10s3ss3">
<span class="header-section-number">10.3.3</span> Simulation error</h3>
<p>We use Monte Carlo simulation to estimate diagnosands. We only get estimates—not the exact value—of diagnosands under a particular model because of simulation error. Simulation error declines as we conduct more simulations. When we conduct many thousands of simulations, we’re relatively certain of the value of the diagnosand under the model. If we conduct just tens of simulations, we are much more uncertain.</p>
<p>We can characterize our uncertainty attending to the diagnosand estimate by calculating a standard error. If the Monte Carlo standard error is large relative to the estimated diagnosand, then we need to increase the number of simulations. Unlike empirical settings where additional data collection can be very expensive, in order to get more observations of diagnostic statistics, we can just increase the number of simulations. Computation time isn’t free—but it’s cheap.</p>
<p>The standard error of diagnosand estimates can be calculated using standard formulas. If the diagnosand can be written as a population mean, and the simulations are fully independent, then we can estimate the standard error as <span class="math inline">\(\frac{\mathrm{sd}(\phi)}{\sqrt{k}}\)</span>, where <span class="math inline">\(k\)</span> is the number of simulations. The power diagnosand summarizes a binary diagnostic statistic (is the estimate significant or not). Binary variables exhibit maximum variability when the probability of a 1 is 0.5. So with 1,000 independent simulations, the standard error for the mean of a binary diagnostic statistic is <span class="math inline">\(\frac{\sqrt{0.5 \times 0.5} }{\sqrt{1000}} = 0.016\)</span>. This level of simulation uncertainty is often acceptable (the 95% confidence interval is approximately 4 * 0.016 = 6.4 percentage points wide), but if it isn’t, you can always increase the number of simulations.</p>
<p>Since some diagnosands are more complex than a population mean (i.e., we can’t characterize the estimation error with simple formulas), so <code>diagnose_design()</code> function uses the nonparametric bootstrap.</p>
</section></section><section id="how-to-diagnose-designs" class="level2" data-number="10.4"><h2 data-number="10.4" class="anchored" data-anchor-id="how-to-diagnose-designs">
<span class="header-section-number">10.4</span> How to diagnose designs</h2>
<section id="sec-ch10s4ss1" class="level3" data-number="10.4.1"><h3 data-number="10.4.1" class="anchored" data-anchor-id="sec-ch10s4ss1">
<span class="header-section-number">10.4.1</span> Exploring design tradeoffs</h3>
<p>Choosing among designs means choosing which diagnosands are important—and not all diagnosands are equally important for every study. For example, in a descriptive study whose goal is to estimate the fraction of people in France who are left-handed, statistical power is irrelevant. A hypothesis test against the null hypothesis that zero percent of the people in France are left-handed is preposterous. We know for sure that the fraction is not zero, we just don’t know its precise value. A much more important diagnosand for this study would be RMSE (root-mean-squared-error), which is a measure of how well-estimated the estimand is that incorporates both bias and variance.</p>
<p>Often, we need to look at several diagnosands in order to understand what might be going wrong. If our design exhibits “undercoverage” (e.g., a procedure for constructing “95%” confidence interval only covers the estimand 50% of the time), that might be because the standard errors are too small or because the point estimator is biased, or some combination of the two. In really perverse instances, we might have a biased point estimator which, thanks to overly-wide confidence intervals, just happens to cover 95% of the time.</p>
<p>Many research design decisions involve trading off bias and variance. In trade-off settings, we may need to accept higher variance in order to decrease bias. Likewise, we may need to accept a bit of bias in order to achieve lower variance. The tradeoff is captured by mean-squared error, which is the average squared distance between <span class="math inline">\(a_d\)</span> and <span class="math inline">\(a_m\)</span>. Of course, we would ideally like to have as low a mean-squared error as possible, that is, we would like to achieve low variance and low bias simultaneously.</p>
<p>To illustrate, consider the following three designs as represented by three targets. The inquiry is the bullseye of the target. The data and answer strategies combine to generate a process by which arrows are shot towards the target. On the left, we have a very bad archer: even though the estimates are unbiased in the sense that they hit the bullseye “on average”, very few of the arrows are on target. In the middle, we have an excellent shot: they are both on target and low variance. On the right, we have an archer who is very consistent (low variance) but biased. The mean squared error is highest on the left and lowest in the middle.</p>
<div id="fig-ch10num5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="../figures/figure-10-5.svg" class="lightbox" title="Visualization of the bias and variance of three ‘estimators’ of the bullseye" data-gallery="quarto-lightbox-gallery-5"><img src="../figures/figure-10-5.svg" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;10.5: Visualization of the bias and variance of three ‘estimators’ of the bullseye</figcaption><p></p>
</figure>
</div>
<p>The archery metaphor is common in research design textbooks because it effectively conveys the difference between variance and bias, but it does elide an important point. It really matters <strong>which target</strong> the archer is shooting at. <a href="#fig-ch10num6">Figure&nbsp;<span>10.6</span></a> shows a bizarre double-target representing two inquiries. The empirical strategy is unbiased and precise for the left inquiry, but it is clearly biased for the right inquiry. When we are describing the properties of an answer strategy, we have to be clear about which inquiry it is associated with.</p>
<div id="fig-ch10num6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="../figures/figure-10-6.svg" class="lightbox" title="The bias, variance, and RMSE of an answer strategy depend on the inquiry." data-gallery="quarto-lightbox-gallery-6"><img src="../figures/figure-10-6.svg" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;10.6: The bias, variance, and RMSE of an answer strategy depend on the inquiry.</figcaption><p></p>
</figure>
</div>
<p>MSE is an exactly equal weighting of variance and bias (squared). Yet many other weightings of these two diagnosands are possible, and different researchers will vary in their weightings.</p>
<p>In evaluating a research design diagnosis, what understand the weighting of all relevant diagnosands. We can think of this as our research design utility function. Our utility function describes how important it is to study big questions, to shift beliefs in a research field, to overturn established findings, to obtain unbiased answers, and to get the sign of the inquiry right. When we compare across empirical designs, we compare them on this utility function that aggregates all the diagnosands according to their importance.</p>
<p>For example, we too often consider the diagnosand power on its own. This diagnosand is the probability of getting a statistically significant result, which of course depends on many things about your design including, crucially, the unknown magnitude of the parameter to be estimated. But considering power alone is also misleading: no researcher wants to design a study that is 80% powered but returns highly biased estimates. Another way of saying this is that researchers always care about both power and bias. How much they care about each feature determines the weight of power and bias in their utility function.</p>
<p>Diagnosands need not be about hypothesis testing or even statistical analysis of the data at all. We often trade off how much we learn from a research design with its cost in terms of money and our time. We have financial and time budgets that provide hard constraints to our designs, but we also at the margin many researchers wish to select cheaper (or shorter) designs in order to carry out more studies or finish their degree sooner. Time and cost are also diagnostic statistics! We may wish to explore the maximum cost of a study or the average amount of time it would take.</p>
<p>Ethical considerations also often enter the process of assessing research designs, if implicitly. We can explicitly incorporate them into our utility function by caring about harm to subjects and the degree of informed consent. When collecting data, researchers often encounter a tradeoff between informing subjects about the purpose of the study (an ethical consideration, or a requirement of the IRB) on the one hand and the bias that comes from Hawthorne or demand effects on the other. We can incorporate these considerations in a research design diagnosis by specifying diagnostic statistics related to the amount of disclosure about the purposes of research or the number of subjects harmed in the research. See <a href="../lifecycle/planning/ethics.html#sec-ch21s1ss1"><span>Section&nbsp;47.1</span></a> for an example.</p>
</section><section id="sec-ch10s4ss2" class="level3" data-number="10.4.2"><h3 data-number="10.4.2" class="anchored" data-anchor-id="sec-ch10s4ss2">
<span class="header-section-number">10.4.2</span> Diagnosis under model uncertainty</h3>
<p>We are always uncertain about the model in <em>M</em>. If we were certain of <em>M</em> (or there was no real dispute about it), there would be no need to conduct new empirical research. Research design diagnosis can incorporate this uncertainty by evaluating the performance of the design under alternative models. For example, if we are unsure of the exact value of the intra-class correlation (ICC), we can simulate the design under a range of plausible ICC values. If we are unsure of the true average treatment effect, we can diagnose the power of the study over a range of plausible effect sizes. Uncertainty over model inputs like the means, variances, and covariances in data that will eventually be collected is a major reason to simulate under a range of plausible values.</p>
<p>We illustrate diagnosis under model uncertainty with the declaration below. Here we have a 200 unit two-arm trial in which we explicitly describe our uncertainty over the value of the true average treatment effect. In the <code>potential_outcomes</code> call, we have <code>Y ~ runif(1, 0, 0.5) * Z + U</code> which indicates that the treatment effect in each run of the simulation is one draw from uniform distribution between 0.0 and 0.5.</p>
<div id="diagnosishetfx" class="definition">
<p>Declaration including model uncertainty</p>
<div class="cell" data-file="scripts_declarations/declaration_10.2.R">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">declaration_10.2</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">declare_model</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="fl">200</span>, U <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,</span>
<span>    <span class="co"># this runif(n = 1, min = 0, max = 0.5) </span></span>
<span>    <span class="co"># generates 1 random ATE between 0 and 0.5</span></span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">1</span>, min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">*</span> <span class="va">Z</span> <span class="op">+</span> <span class="va">U</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span>ATE <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Y_Z_1</span> <span class="op">-</span> <span class="va">Y_Z_0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_assignment</span><span class="op">(</span>Z <span class="op">=</span> <span class="fu">complete_ra</span><span class="op">(</span><span class="va">N</span>, prob <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_measurement</span><span class="op">(</span>Y <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">Z</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">Z</span>, inquiry <span class="op">=</span> <span class="st">"ATE"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="lem-ch10num4" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 10.4 </strong></span>Diagnosis under model uncertainty</p>
<div class="cell">

</div>
<p><a href="#fig-ch10num7">Figure&nbsp;<span>10.7</span></a> shows how the statistical power of this design varies over the set of model possibilities. We plot the possible effect sizes we entertain in the model on the horizontal axis and the statistical power on the vertical axis. We also plot a loess curve flexibly smooths over the full distribution of effect sizes. We see that at low levels of the effect size, statistical power is quite poor. With only 200 subjects, we couldn’t achieve 80% statistical power unless the true effect size were approximately 0.45 standard deviations. The effect size at which a design achieves 80% power is often referred to as the minimum detectable effect size (MDE). This exercise shows how the MDE diagnosand is a summary of a design that admits uncertainty over the effect size. We return to this example in <a href="#sec-ch10s4ss2"><span>Section&nbsp;10.4.2</span></a>, when we redesign this study to learn how the MDE changes at different sample sizes.</p>
<p>What is “the” power of this design? Under one view, the true power of the design is the whichever value for power is associated with the effect size. But under an agnostic view, the ex ante “power” of the design is a weighted average of all these power values, weighted by the researcher’s prior beliefs over the distribution of possible effect sizes.</p>
<div id="fig-ch10num7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="../figures/figure-10-7.svg" class="lightbox" title="Diagnosing an experiment over uncertainty about the true effect size" data-gallery="quarto-lightbox-gallery-7"><img src="../figures/figure-10-7.svg" class="img-fluid figure-img"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;10.7: Diagnosing an experiment over uncertainty about the true effect size</figcaption><p></p>
</figure>
</div>
</div>
</section><section id="adjudicating-between-competing-models" class="level3" data-number="10.4.3"><h3 data-number="10.4.3" class="anchored" data-anchor-id="adjudicating-between-competing-models">
<span class="header-section-number">10.4.3</span> Adjudicating between competing models</h3>
<p>The principle to design agnostically extends to <em>competing</em> models. Imagine that you believe <span class="math inline">\(M1\)</span> is true but that your scholarly rival believes <span class="math inline">\(M2\)</span>. Suppose that under <span class="math inline">\(M1\)</span>, the treatment affects <span class="math inline">\(Y1\)</span> but not <span class="math inline">\(Y2\)</span>. Your rival posits the reverse: Under <span class="math inline">\(M2\)</span>: the treatment affects <span class="math inline">\(Y2\)</span> but not <span class="math inline">\(Y1\)</span>. In the spirit of scientific progress, the both of you engage in an “adversarial collaboration.” You design a study together. The design you choose should, first, demonstrate <span class="math inline">\(M1\)</span> is true if it is true and, second, demonstrate <span class="math inline">\(M2\)</span> is true if <em>it</em> is true. In order to come to an agreement about the properties of the design, you will need to simulate the design under both models.</p>
<div id="diagnosisadjudicating" class="definition">
<p>Declaration of competing models</p>
<div class="cell" data-file="scripts_declarations/declaration_10.3.R">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">M1</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">declare_model</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="fl">200</span>,</span>
<span>    U <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,</span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="fl">0.2</span> <span class="op">*</span> <span class="va">Z</span> <span class="op">+</span> <span class="va">U</span><span class="op">)</span>,</span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">Y2</span> <span class="op">~</span> <span class="fl">0.0</span> <span class="op">*</span> <span class="va">Z</span> <span class="op">+</span> <span class="va">U</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">M2</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">declare_model</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="fl">200</span>,</span>
<span>    U <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,</span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="fl">0.0</span> <span class="op">*</span> <span class="va">Z</span> <span class="op">+</span> <span class="va">U</span><span class="op">)</span>,</span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">Y2</span> <span class="op">~</span> <span class="fl">0.2</span> <span class="op">*</span> <span class="va">Z</span> <span class="op">+</span> <span class="va">U</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">IDA</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span>ATE1 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Y1_Z_1</span> <span class="op">-</span> <span class="va">Y1_Z_0</span><span class="op">)</span>,</span>
<span>                  ATE2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Y2_Z_1</span> <span class="op">-</span> <span class="va">Y2_Z_0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_assignment</span><span class="op">(</span>Z <span class="op">=</span> <span class="fu">complete_ra</span><span class="op">(</span><span class="va">N</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_measurement</span><span class="op">(</span>Y1 <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="va">Z</span><span class="op">)</span>,</span>
<span>                      Y2 <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">Y2</span> <span class="op">~</span> <span class="va">Z</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span><span class="va">Y1</span> <span class="op">~</span> <span class="va">Z</span>, inquiry <span class="op">=</span> <span class="st">"ATE1"</span>, label <span class="op">=</span> <span class="st">"DIM1"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span><span class="va">Y2</span> <span class="op">~</span> <span class="va">Z</span>, inquiry <span class="op">=</span> <span class="st">"ATE2"</span>, label <span class="op">=</span> <span class="st">"DIM2"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">declaration_10.3a</span> <span class="op">&lt;-</span> <span class="va">M1</span> <span class="op">+</span> <span class="va">IDA</span></span>
<span><span class="va">declaration_10.3b</span> <span class="op">&lt;-</span> <span class="va">M2</span> <span class="op">+</span> <span class="va">IDA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="lem-ch10num5" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 10.5 </strong></span>Diagnosis of competing models</p>
<p>To diagnose these alternative models, we count up how frequently each perspective receives support. If we define support by statistical significance (other metrics are of course possible), then your model is supported if the effect of treatment on <span class="math inline">\(Y1\)</span> is significant but the effect on <span class="math inline">\(Y2\)</span> is not significant. If the reverse pattern is obtained, your rival can claim victory. Two kinds of split decisions are possible: neither estimate is significant, or both are. By simulation, we can estimate the rates of these four possibilities, both under your beliefs and those of your theoretical adversary.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">diagnosis_10.5</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">diagnose_design</span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">declaration_10.3a</span>, <span class="va">declaration_10.3b</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-adjudicating" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Table&nbsp;10.7:  Design diagnosis under two alternative theories </caption>
 <thead><tr>
<th style="text-align:center;"> design </th>
   <th style="text-align:center;"> Only theory 1 supported </th>
   <th style="text-align:center;"> Only theory 2 supported </th>
   <th style="text-align:center;"> Both supported </th>
   <th style="text-align:center;"> Neither supported </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:center;"> design_1 </td>
   <td style="text-align:center;"> 0.2610 </td>
   <td style="text-align:center;"> 0.026 </td>
   <td style="text-align:center;"> 0.0260 </td>
   <td style="text-align:center;"> 0.687 </td>
  </tr>
<tr>
<td style="text-align:center;"> design_2 </td>
   <td style="text-align:center;"> 0.0255 </td>
   <td style="text-align:center;"> 0.260 </td>
   <td style="text-align:center;"> 0.0255 </td>
   <td style="text-align:center;"> 0.689 </td>
  </tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The diagnosis shows that the study is responsive to the truth. When theory 1 is correct, the design is more likely to yield empirical evidence in favor of it; the reverse holds when theory 2 is correct. That said, the major concern facing this adversarial collaboration is that the study is too small to resolve the dispute. About two-thirds of the time—regardless of who is right!—neither theory receives support. This problem can be ameliorated either by elaborating more tests of each theoretical perspective or by increasing the size of the study.</p>
</div>
</section></section><section id="summary" class="level2" data-number="10.5"><h2 data-number="10.5" class="anchored" data-anchor-id="summary">
<span class="header-section-number">10.5</span> Summary</h2>
<p>Diagnosis is the process of estimating the properties of research designs under uncertain beliefs about the world. We simulate under many alternative designs because we want to choose designs that are strong under a large range of model possibilities. Each run of a simulate generates a diagnostic statistic. We learn about the distribution of the diagnostic statistic by running the simulation repeatedly. Diagnosands are summaries of the distribution of diagnostic statistics. Which diagnosands are most important will vary from study to study, and depend on the relative weight you place on one diagnosand versus another. Analytic design diagnosis is possible and can be quite powerful—we nevertheless recommend full simulation of research designs in order to learn about a range of diagnosands.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-Gelman2014b" class="csl-entry" role="doc-biblioentry">
Gelman, Andrew, and John Carlin. 2014. <span>“Beyond Power Calculations Assessing Type s (Sign) and Type m (Magnitude) Errors.”</span> <em>Perspectives on Psychological Science</em> 9 (6): 641–51.
</div>
<div id="ref-Gerber2012" class="csl-entry" role="doc-biblioentry">
Gerber, Alan S., and Donald P. Green. 2012. <em><span class="nocase">Field Experiments: Design, Analysis, and Interpretation</span></em>. New York: W.W. Norton.
</div>
<div id="ref-imai2009essential" class="csl-entry" role="doc-biblioentry">
Imai, Kosuke, Gary King, and Clayton Nall. 2009. <span>“The Essential Role of Pair Matching in Cluster-Randomized Experiments, with Application to the Mexican Universal Health Insurance Evaluation.”</span> <em>Statistical Science</em> 24 (1): 29–53.
</div>
<div id="ref-imai2008essential" class="csl-entry" role="doc-biblioentry">
Imai, Kosuke, Gary King, and Elizabeth A. Stuart. 2008. <span>“Misunderstandings Between Experimentalists and Observationalists about Causal Inference.”</span> <em>Journal of the Royal Statistical Society: Series A (Statistics in Society)</em> 171 (2): 481–502.
</div>
<div id="ref-middleton2008bias" class="csl-entry" role="doc-biblioentry">
Middleton, Joel A. 2008. <span>“Bias of the Regression Estimator for Experiments Using Clustered Random Assignment.”</span> <em>Statistics &amp; Probability Letters</em> 78 (16): 2654–59.
</div>
<div id="ref-morrisetal2019" class="csl-entry" role="doc-biblioentry">
Morris, Tim P., Ian R. White, and Michael J. Crowther. 2021. <span>“Using Simulation Studies to Evaluate Statistical Methods.”</span> <em>Statistics in Medicine</em> 38 (11): 2074–2102.
</div>
<div id="ref-samii2012equivalencies" class="csl-entry" role="doc-biblioentry">
Samii, Cyrus, and Peter M. Aronow. 2012. <span>“On Equivalencies Between Design-Based and Regression-Based Variance Estimators for Randomized Experiments.”</span> <em>Statistics &amp; Probability Letters</em> 82 (2): 365–70.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../declaration-diagnosis-redesign/redesigning.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Redesigning</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../declaration-diagnosis-redesign/design-example.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Design example</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"selector":".lightbox","descPosition":"bottom","openEffect":"zoom","closeEffect":"zoom","loop":true});</script>


</body></html>