# Meta-analysis {.unnumbered}


```{r}
#| echo: false
#| include: false
#| purl:  false
source("scripts/before_chapter_script.R")
```

One of the last stages of the lifecycle of a research design is its eventual incorporation in to our common scientific understanding of the world. Research findings are synthesized into our broader scientific understanding through systematic reviews and meta-analysis. 

Research synthesis takes two basic forms. The first is meta-analysis, in which a series of estimates are analyzed together in order to better understand features of the distribution of answers obtained in the literature (see Section @meta-analysis). Studies can be averaged together in ways that are better and worse. Sometimes the answers are averaged together according to their precision. A precision-weighted average gives more weight to precise estimates and less weight to studies that are noisy. Sometimes studies are "averaged" by counting up how many of the estimates are positive and significant, how many are negative and significant, and how many are null. This is the typical approach taken in a literature review. Regardless of the averaging approach, the goal of this kind of synthesis is to learn as much as possible about a particular inquiry *I* by drawing on evidence from many studies.

A second kind of synthesis is an attempt to bring together the results of many designs, each of which targets a different inquiry about a common model. This is the kind of synthesis that takes place across an entire research literature. Different scholars focus on different nodes and edges of the common model, so a synthesis needs to incorporate the diverse sources of evidence. Such synthesis strategies include for example Bayesian model averaging approaches and stacking approaches (see e.g. @yao2018using). 

How can you best anticipate how your research findings will be synthesized? For the first kind of synthesis---meta-analysis---you must be cognizant of keeping a commonly understood *I* in mind. You want to select inquiries not for their novelty, but because of their commonly-understood importance. While the specifics of the model *M* might differ from study to study, the fact that the *I*s are all similar enough to be synthesized allows for a specific kind of knowledge accumulation.

For the second kind of synthesis---literature-wide progress on a full causal model---even greater care is required. Specific studies cannot make up bespoke models *M* but instead must understand how the specific *M* adopted in the study is a special case of some broader *M* that is in principle agreed to by a wider research community. Perhaps in this spirit, @Samii2016 sets role of "causal empiricists" apart from the role of theorists. The nonstop, never-ending proliferation of study-specific theories is a threat to this kind of knowledge accumulation. In a telling piece, @mcphetres_2020 document that in a decade of research articles published in *Psychological Science*, 359 specific theories were named. Of these 70% were named just once and a further 12% were named just twice.

Design then with a view to integration. In the ideal case the meta-analytic design will already exist and your job will be to design a new study that can demonstrably add value to the collective design.

