# Research Design Library

This section of the book enumerates a series of common social science research designs. Each entry will include a description of the design in terms of its model, inquiry, data strategy, and answer strategy, first in words then in code.We'll often diagnose designs over the range of values of some design parameters in order to point out especially interesting or important features of the design.

Our goal in this section is not to provide a comprehensive accounting of all empirical research designs. It's also not to describe any of the particular designs in exhaustive detail, because we are quite sure that in order for these designs to be useful for any practical purpose, they will need to be modified. The entries in the design library are not recipes that will automatically produce high-quality research. Instead, we hope that the entries provide inspiration for how to tailor a particular class of design to your own research setting.

The design library is also a corpus of design elements and code that can be mixed-and-matched to fit your particular research setting. We do not have a stepped-wedge experimental design with blocking, but you can create one if that is your design by combining elements from the stepped-wedge design and the block-randomized experimental design.

We've organized the library by inquiry and by data strategy. Inquiries can be descriptive or causal; data strategies can be observational or experimental. Crossing these two pairs gives rise to four categories of research design: observational descriptive, experimental descriptive, observational causal, and experimental causal. Table @tbl-designtypes offers examples of each class of design. We dedicate chapters to each of these four as well as a chapter for "complex" designs -- designs that involve multiple stages, multiple inquiries, or inferences from multiple distinct projects. 

|                          | Data strategy: Observational                       | Data strategy: Experimental                |
|------------------------- | -------------------------------------------------- | ------------------------------------------ |
| **Inquiry: Descriptive** | Sample survey or case study                        | List experiment or participant observation |
| **Inquiry: Causal**      | Regression discontinuity design or process tracing | Randomized controlled trial                |

: Research design types with examples. {#tbl-designtypes} 

