<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Research Design in the Social Sciences - 16&nbsp; Observational : causal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../library/experimental-descriptive.html" rel="next">
<link href="../library/observational-descriptive.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style type="text/css" media="print">
    body { visibility: hidden; display: none }
</style>
<script type="text/javascript">
    function createCookie(name, value, days) {
        var expires;
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (7 * 24 * 60 * 60 * 1000));
            expires = "; expires=" + date.toGMTString();
        }
        else {
            expires = "";
        }
        document.cookie = name + "=" + value + expires + "; path=/";
    }
    
    function getCookie(c_name) {
        if (document.cookie.length > 0) {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1) {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) {
                    c_end = document.cookie.length;
                }
                return unescape(document.cookie.substring(c_start, c_end));
            }
        }
        return "";
    }
    window.onload = () => {
      if (getCookie('popupShown') != 'yes') {
        const myModal = new bootstrap.Modal('#exampleModal');
        myModal.show();
        createCookie('popupShown', 'yes', 1)
      }
    }
</script><script src="../site_libs/kePrint-0.0.1/kePrint.js"></script><link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../library/">Research design library</a></li><li class="breadcrumb-item"><a href="../library/observational-causal.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Observational : causal</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Research Design in the Social Sciences</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../acknowledgements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/what-is-a-research-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">What is a research design?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/research-design-principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Research design principles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../introduction/getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Getting started</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Declaration, Diagnosis, Redesign</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/declaring-designs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Declaring designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/specifying-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Specifying the model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/defining-inquiry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Defining the inquiry</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/crafting-research-strategy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Crafting a data strategy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/choosing-answer-strategy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Choosing an answer strategy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/redesigning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Redesigning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/diagnosing-designs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Diagnosing designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/design-example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Design example</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../declaration-diagnosis-redesign/declaration-in-code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Designing in code</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../library/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Research design library</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Observational : descriptive</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/observational-causal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Observational : causal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Experimental : descriptive</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/experimental-causal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Experimental : causal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../library/complex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Complex designs</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../lifecycle/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Research design lifecycle</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/planning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Planning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/realization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Realization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../lifecycle/integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Integration</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Epilogue</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../errata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Errata</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<p align="center">
<a style="color: black; text-decoration: none; font-size: 17px" target="_new" href="https://press.princeton.edu/books/paperback/9780691199573/research-design-in-the-social-sciences"> <img style="border: 1px solid darkgray; margin-bottom: 5px" width="100px" src="../figures/cover.jpg"><br>Preorder book</a>
</p>
</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
    <ul>
<li>
<a href="#sec-ch16s1" id="toc-sec-ch16s1" class="nav-link active" data-scroll-target="#sec-ch16s1"><span class="header-section-number">16.1</span> Process tracing</a>
    <ul class="collapse">
<li><a href="#design-examples" id="toc-design-examples" class="nav-link" data-scroll-target="#design-examples"><span class="header-section-number">16.1.1</span> Design examples</a></li>
    </ul>
</li>
    <li>
<a href="#sec-ch16s2" id="toc-sec-ch16s2" class="nav-link" data-scroll-target="#sec-ch16s2"><span class="header-section-number">16.2</span> Selection-on-observables</a>
    <ul class="collapse">
<li><a href="#design-examples-1" id="toc-design-examples-1" class="nav-link" data-scroll-target="#design-examples-1"><span class="header-section-number">16.2.1</span> Design examples</a></li>
    </ul>
</li>
    <li>
<a href="#sec-ch16s3" id="toc-sec-ch16s3" class="nav-link" data-scroll-target="#sec-ch16s3"><span class="header-section-number">16.3</span> Difference-in-differences</a>
    <ul class="collapse">
<li><a href="#design-examples-2" id="toc-design-examples-2" class="nav-link" data-scroll-target="#design-examples-2"><span class="header-section-number">16.3.1</span> Design examples</a></li>
    </ul>
</li>
    <li>
<a href="#sec-ch16s4" id="toc-sec-ch16s4" class="nav-link" data-scroll-target="#sec-ch16s4"><span class="header-section-number">16.4</span> Instrumental variables</a>
    <ul class="collapse">
<li><a href="#design-examples-3" id="toc-design-examples-3" class="nav-link" data-scroll-target="#design-examples-3"><span class="header-section-number">16.4.1</span> Design examples</a></li>
    </ul>
</li>
    <li>
<a href="#sec-ch16s5" id="toc-sec-ch16s5" class="nav-link" data-scroll-target="#sec-ch16s5"><span class="header-section-number">16.5</span> Regression discontinuity designs</a>
    <ul class="collapse">
<li><a href="#design-examples-4" id="toc-design-examples-4" class="nav-link" data-scroll-target="#design-examples-4"><span class="header-section-number">16.5.1</span> Design examples</a></li>
    </ul>
</li>
    </ul>
<ul><li><a class="navlink nav-link" href="https://doi.org/10.7910/DVN/HYVPO5" data-scroll-target="https\://doi.org/10.7910/DVN/HYVPO5">Replication code and data</a></li></ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body" style="text-align: center">
        <img width="400px" src="https://book.declaredesign.org/figures/cover.jpg" style="margin-bottom: 15px"><br>
        Available for preorder from Princeton University Press
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <!--<button type="button" class="btn btn-primary">Buy book</button>-->
        <a href="https://www.amazon.com/Research-Design-Social-Sciences-Declaration/dp/0691199574/?&amp;_encoding=UTF8&amp;tag=declaredesign-20&amp;linkCode=ur2&amp;linkId=84be1f952d1d7aaaa5be867eade93474&amp;camp=1789&amp;creative=9325" target="_blank" class="btn btn-info" role="button">Amazon</a>
        <a href="https://press.princeton.edu/books/paperback/9780691199573/research-design-in-the-social-sciences" target="_blank" class="btn btn-info" role="button">Princeton University Press</a>
      </div>
    </div>
  </div>
</div>

<header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Observational : causal</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>In an observational design, researchers do not themselves assign units to conditions; the natural processes of the world are responsible for the observed treatment conditions. Causal inference from observational research designs is the art of imagining what outcomes treated units would have expressed if they had not been treated – and the outcomes of the untreated units if they had been treated.</p>
<p>Observational causal inference is hard because it depends on the world generating just the right circumstances. Process tracing requires observation of just the right clues to the causal mystery. Selection-on-observables requires measurement of a set of variables that collectively close all the backdoor paths from treatment to outcome. A difference-in-difference design requires a very specific kind of over-time stability — that untreated potential outcomes move exactly in parallel. Instrumental variables designs require nature to randomly assign something we can measure. Regression discontinuity designs requires a cutoff that determines who is treated and who is not that we can observe and understand.</p>
<p>These are five of the big observational causal research designs. Many additional innovative designs have been developed to try to estimate causal quantities from observational research designs. These generally seek clever innovations in <span class="math inline">\(A\)</span> in order to have as few assumptions on <span class="math inline">\(M\)</span> as possible. We refer readers to <span class="citation" data-cites="angrist2008mostly">Angrist and Pischke (<a href="../references.html#ref-angrist2008mostly" role="doc-biblioref">2008</a>)</span> and <span class="citation" data-cites="dunning2012natural">Dunning (<a href="../references.html#ref-dunning2012natural" role="doc-biblioref">2012</a>)</span> for excellent overviews of the design theory behind many of these methods.</p>
<section id="sec-ch16s1" class="level2" data-number="16.1"><h2 data-number="16.1" class="anchored" data-anchor-id="sec-ch16s1">
<span class="header-section-number">16.1</span> Process tracing</h2>
<div class="ddbox">
<p>We declare a qualitative design in which researchers seek to learn about the effect of a cause on a single unit. The diagnosis helps evaluate the gains from different within-case data gathering strategies.</p>
</div>
<p>In qualitative research we are often interested in learning about the causal effect for a single unit. For example, for a country unit that underwent sanctions (an “event”), we want to know the causal effect of the sanctions on government behavior. To do so, we need to know what would have happened if the event did not happen, the <em>counter</em>factual outcome that did not occur as opposed to the factual outcome that did. Due to the fundamental problem of causal inference, we cannot observe what would have happened if that counterfactual case had happened. We have to guess—or infer—what would have happened. Social scientists have developed a large array of tools for guessing missing counterfactual outcomes — what would have happened in the counterfactual case, if the event had not happened.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>A common inquiry in this setting is whether an outcome was <em>due</em> to a cause. For instance in a case with <span class="math inline">\(X=1, Y=1\)</span>, this “causal attribution” inquiry or “Cause of Effect” inquiry can be written <span class="math inline">\(\mathrm{CoE}:=1-Y(0)| X=1 \mathrm{ \&amp; } Y=1\)</span>. For a unit with <span class="math inline">\(X=1\)</span> and <span class="math inline">\(Y=1\)</span>, <span class="math inline">\(\mathrm{CoE}=1\)</span> if <span class="math inline">\(Y(0)=0\)</span>.</p>
<p>“Process tracing” is a prominent strategy for assessing causes of effects <span class="citation" data-cites="BennettCheckel2015PT fairfield2017explicit">(<a href="../references.html#ref-BennettCheckel2015PT" role="doc-biblioref">Bennett and Checkel 2015</a>; <a href="../references.html#ref-fairfield2017explicit" role="doc-biblioref">Fairfield and Charman 2017</a>)</span>. Here, following for example <span class="citation" data-cites="humphreys2017qualitative">Humphreys and Jacobs (<a href="../references.html#ref-humphreys2017qualitative" role="doc-biblioref">forthcoming</a>)</span>, we think of process tracing as a procedure in which researchers provide a theory in the form of a causal model that is rich enough to characterize the probability of observing ancillary data (“Causal process observations” <span class="citation" data-cites="brady2004data">(<a href="../references.html#ref-brady2004data" role="doc-biblioref">Brady 2004</a>)</span>) given underlying causal relations. When equipped with prior beliefs, such a model in turn lets one use Bayes’ rule to form posterior beliefs over causal relations after observing these data.</p>
<p>For intuition, say we are interested in whether a policy caused a change in economic outcomes. We theorize that for the policy to matter, it at least had to be implemented. So if we find out that the policy was not implemented we infer that it did not matter. We make theory-dependent inferences that are reasonable <em>insofar as</em> the theory itself is reasonable. In this example, if there are plausible channels through which a policy might have mattered even if not implemented, then our conclusion would not be warranted.</p>
<p>To illustrate design choices for a process tracing study we consider a setting in which we have already observed <span class="math inline">\(X, Y\)</span> data and we are interested in figuring out whether <span class="math inline">\(Y\)</span> takes on the value it does <em>because</em> <span class="math inline">\(X\)</span> took on the value it did.</p>
<p>More specifically we imagine a model with two ancillary variables, <span class="math inline">\(M\)</span> and <span class="math inline">\(W\)</span>. We posit that <span class="math inline">\(X\)</span> causes <span class="math inline">\(Y\)</span> via <span class="math inline">\(M\)</span>—with negative effects of <span class="math inline">\(X\)</span> on <span class="math inline">\(M\)</span> and of <span class="math inline">\(M\)</span> and <span class="math inline">\(Y\)</span> ruled out. And we posit that <span class="math inline">\(W\)</span> is a cause of both <span class="math inline">\(M\)</span> and <span class="math inline">\(Y\)</span>. Specifically, our model asserts that if <span class="math inline">\(W=1\)</span> then <span class="math inline">\(X\)</span> causes <span class="math inline">\(M\)</span> and <span class="math inline">\(M\)</span> causes <span class="math inline">\(Y\)</span> for sure. Under this model <span class="math inline">\(M\)</span> and <span class="math inline">\(W\)</span> each serve as “clues” for the causal effect of <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span>.</p>
<p>Using the language popularized by <span class="citation" data-cites="VanEvera1997">Van Evera (<a href="../references.html#ref-VanEvera1997" role="doc-biblioref">1997</a>)</span>, <span class="math inline">\(M\)</span> provides a “hoop” test: if you look for data on <span class="math inline">\(M\)</span> and find that <span class="math inline">\(M=0\)</span> when <span class="math inline">\(X=1\)</span> and <span class="math inline">\(Y=1\)</span> then you infer that <span class="math inline">\(X\)</span> did not cause <span class="math inline">\(Y\)</span>. If on the other hand you examine <span class="math inline">\(W\)</span> and find that <span class="math inline">\(W=1\)</span> then you have a “smoking gun” test: You infer that <span class="math inline">\(X\)</span> did indeed cause <span class="math inline">\(Y\)</span>. However, if you find both <span class="math inline">\(M=0\)</span> and <span class="math inline">\(W=1\)</span>, then you know your model is wrong.</p>
<p>The model can be described using the <code>CausalQueries</code> package thus:</p>
<div class="cell" data-file="scripts_declarations/declaration_16.1a.R">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">rdss</span><span class="op">)</span> <span class="co"># for helper functions</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">CausalQueries</span><span class="op">)</span></span>
<span></span>
<span><span class="va">causal_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/CausalQueries/man/make_model.html">make_model</a></span><span class="op">(</span><span class="st">"X -&gt; M -&gt; Y &lt;- W -&gt; M"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/CausalQueries/man/set_restrictions.html">set_restrictions</a></span><span class="op">(</span><span class="st">"(M[X=1] &lt; M[X=0]) | (M[X=1, W=1] == M[X=0, W=1])"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/CausalQueries/man/set_restrictions.html">set_restrictions</a></span><span class="op">(</span><span class="st">"(Y[M=1] &lt; Y[M=0]) | (Y[M=1, W=1] == Y[M=0, W=1])"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">strategies</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X-Y"</span>, <span class="st">"X-Y-M"</span>, <span class="st">"X-Y-W"</span>,  <span class="st">"X-Y-W-M"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The DAG of the causal model is shown in <a href="#fig-ch16num1">Figure&nbsp;<span>16.1</span></a>.</p>
<div id="fig-ch16num1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-1.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.1: Directed acyclic graph of a process tracing model</figcaption></figure>
</div>
<p>This model definition describes the DAG but also specifies a set of restrictions on causal relations. By default, flat priors are then placed over all other possible causal relations, though of course other prior beliefs could also be specified.</p>
<p>We now have all we need to assess what inferences we might make given different sorts of observations on <span class="math inline">\(W\)</span> and <span class="math inline">\(M\)</span>.</p>
<p><a href="#tbl-ptprobative">Table&nbsp;<span>16.1</span></a> shows three types of quantities: beliefs upon observing <span class="math inline">\(X=1, Y=1\)</span>, conditional inferences upon observing additional data on <span class="math inline">\(M\)</span> or <span class="math inline">\(W\)</span>, and the conditional probability of seeing different outcomes for <span class="math inline">\(M\)</span> or <span class="math inline">\(W\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ptprobative" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;16.1: Beliefs about the probability <span class="math inline">\(X\)</span> caused <span class="math inline">\(Y\)</span> upon observing <span class="math inline">\(X=1, Y=1\)</span>, updated inferences upon observing additional data on <span class="math inline">\(M\)</span> or <span class="math inline">\(W\)</span>, and the conditional probability of seeing different outcomes for <span class="math inline">\(M\)</span> or <span class="math inline">\(W\)</span> given observation of <span class="math inline">\(X=1, Y=1\)</span>.</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Query</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Prob(CoE=1|X = 1, Y=1)</td>
<td style="text-align: center;">0.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prob(CoE=1 | X = 1, Y = 1, M=0)</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prob(CoE=1 | X = 1, Y = 1, M=1)</td>
<td style="text-align: center;">0.77</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prob(CoE=1 | X = 1, Y = 1, W=0)</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prob(CoE=1 | X = 1, Y = 1, W=1)</td>
<td style="text-align: center;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prob(M=1 | X = 1, Y = 1)</td>
<td style="text-align: center;">0.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prob(W=1 | X = 1, Y = 1)</td>
<td style="text-align: center;">0.64</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>We see here that <span class="math inline">\(M\)</span> provides a hoop test since we are certain that <span class="math inline">\(X\)</span> does not cause <span class="math inline">\(Y\)</span> when <span class="math inline">\(M=0\)</span>, but we are uncertain when <span class="math inline">\(M=1\)</span>. (Moreover, we already expect to see <span class="math inline">\(M=1\)</span> given what we have seen for <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>). <span class="math inline">\(W\)</span> provides a smoking gun test since we are certain that <span class="math inline">\(X\)</span> causes <span class="math inline">\(Y\)</span> when <span class="math inline">\(M=1\)</span> but uncertain otherwise. Since we have access to both conditional inferences and the probability of seeing different types of data, we have enough data in <a href="#tbl-ptprobative">Table&nbsp;<span>16.1</span></a> to calculate how different strategies will perform.</p>
<p>We think it useful to fold these quantities into a design declaration so that research consumers can access the data strategies and answer strategies in the same way as they would for any other problem.</p>
<p><a href="#def-ch16num1">Declaration&nbsp;<span>16.1</span></a> provides a flexible process tracing design. You can use this design with a different causal model and substituting in different causal queries and process tracing strategies. Given a background causal model, the design first draws a “causal type”—that is a case together with all its causal relations. The value of the estimand (EoC) can then be calculated and the observable data corresponding to the type revealed. The estimation uses a custom function, which simply returns the inferences on the query—like those in the <a href="#tbl-ptprobative">Table&nbsp;<span>16.1</span></a>—but given different possible observed values for all nodes. No data strategy is provided explicitly as this is tied up here in the estimation, that is, the estimation step describes what data will be used.</p>
<div id="def-ch16num1" class="declaration theorem definition">
<p><span class="theorem-title"><strong>Declaration 16.1 </strong></span>Process tracing design declaration</p>
<div class="cell" data-file="scripts_declarations/declaration_16.1b.R">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">declaration_16.1</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">declare_model</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/CausalQueries/man/draw_causal_type.html">draw_causal_type</a></span><span class="op">(</span><span class="va">causal_model</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span></span>
<span>    CoE <span class="op">=</span>  <span class="fu"><a href="https://rdrr.io/pkg/CausalQueries/man/query_distribution.html">query_distribution</a></span><span class="op">(</span></span>
<span>      <span class="va">causal_model</span>, </span>
<span>      query <span class="op">=</span> <span class="st">"Y[X=1] - Y[X=0]"</span>, </span>
<span>      parameters <span class="op">=</span> <span class="va">causal_type</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_measurement</span><span class="op">(</span></span>
<span>    handler <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span>
<span>      <span class="va">causal_model</span> <span class="op">|&gt;</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/pkg/CausalQueries/man/make_data.html">make_data</a></span><span class="op">(</span>parameters <span class="op">=</span> <span class="va">data</span><span class="op">$</span><span class="va">causal_type</span><span class="op">)</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span></span>
<span>    handler <span class="op">=</span> <span class="fu">label_estimator</span><span class="op">(</span><span class="va">process_tracing_estimator</span><span class="op">)</span>, </span>
<span>    causal_model <span class="op">=</span> <span class="va">causal_model</span>,</span>
<span>    query <span class="op">=</span> <span class="st">"Y[X=1] - Y[X=0]"</span>,</span>
<span>    strategies <span class="op">=</span> <span class="va">strategies</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="lem-ch16num1" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 16.1 </strong></span>Process tracing diagnosis</p>
<p>Given such a model, a case in which <span class="math inline">\(X = Y = 1\)</span> (for instance), and limited resources, we now want to know whether we would be better gathering data on <span class="math inline">\(M\)</span> or on <span class="math inline">\(W\)</span> or both.</p>
<p>The answers are given in <a href="#fig-ch16num2">Figure&nbsp;<span>16.2</span></a>. Here we show the expected error from inferences given each process tracing strategy. We break up the diagnoses according to the <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span> data already observed—thus illustrating how an unconditional model can be used to assess designs even after some data is observed. Across the four possible data patterns we see equivalent implications for settings in which we are interested in a case with <span class="math inline">\(X=Y=1\)</span> and a case with <span class="math inline">\(X=Y=0\)</span>. For the cases with <span class="math inline">\(X \neq Y\)</span> we already know—because of the monotonicity restrictions in the model—that <span class="math inline">\(X\)</span> did not cause <span class="math inline">\(Y\)</span> and so we learn nothing from all strategies.</p>
<p>We see only modest declines in expected errors from observation of the mediator <span class="math inline">\(M\)</span> (consistent with the manual calculation above), but large declines from observing <span class="math inline">\(W\)</span>. If we already observe <span class="math inline">\(W\)</span> the gains from observing <span class="math inline">\(M\)</span> are still more slight. Broadly this confirms a more general observation that mediators can provide limited traction for learning about causes of effects relative to moderators <span class="citation" data-cites="dawid2022bounding">(<a href="../references.html#ref-dawid2022bounding" role="doc-biblioref">Dawid, Humphreys, and Musio 2022</a>)</span>.</p>
<div id="fig-ch16num2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-2.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.2: Inferences from four different process tracing data strategies on whether <span class="math inline">\(X\)</span> caused <span class="math inline">\(Y\)</span> given four different observed <span class="math inline">\(X,Y\)</span> data patterns.</figcaption></figure>
</div>
</div>
<section id="design-examples" class="level3" data-number="16.1.1"><h3 data-number="16.1.1" class="anchored" data-anchor-id="design-examples">
<span class="header-section-number">16.1.1</span> Design examples</h3>
<ul>
<li><p><span class="citation" data-cites="REVKIN2020104981">Revkin and Ahram (<a href="../references.html#ref-REVKIN2020104981" role="doc-biblioref">2020</a>)</span> consider the “rebel social contract” in which rebel groups offer citizens political protections and social benefits in return for citizens’ allegiance. The authors use the presence of formal complaints by citizens about the Islamic State in Iraq and Syria as a hoop test for the causal model of exchange of protections for allegiance.</p></li>
<li><p><span class="citation" data-cites="snyder_borghard_2011">Snyder and Borghard (<a href="../references.html#ref-snyder_borghard_2011" role="doc-biblioref">2011</a>)</span> attempt to apply a smoking gun test to audience cost theory, but could find no clear cut cases of settings in which “the public was opposed to military action before a threat was issued and then explicitly punished the leader for not following through with a threat with which it disagreed.”</p></li>
</ul></section></section><section id="sec-ch16s2" class="level2" data-number="16.2"><h2 data-number="16.2" class="anchored" data-anchor-id="sec-ch16s2">
<span class="header-section-number">16.2</span> Selection-on-observables</h2>
<div class="ddbox">
<p>We declare a design in which a researcher tries to address concerns about confounding by conditioning on other observable variables. In the design the researcher has to specify how the other variable creates a risk of confounding and how exactly they will take account of these variables to minimize bias.</p>
</div>
<p>When we want to learn about causal effects, but treatments are allocated by the world and not by the researcher, we are sometimes stuck. It is possible that a comparison of treated units to control units will generate biased inferences because of selection – the problem that certain types of units “select” into treatment and others into control. If the average potential outcomes of the groups that come to be treated or untreated are not equal, then a comparison of the realized outcomes of the two groups will yield biased causal inferences.</p>
<p>Sometimes, however, we know enough about selection in order to condition on the variables that cause it. A selection-on-observables design stipulates a family of models <span class="math inline">\(M\)</span> of the world that describe which variables are responsible for selection, then employs a data strategy that measures those variables, rendering them “observable.” In the answer strategy, we draw on substantive knowledge of the causal process to generate an “adjustment set,” or a set of variables that predict selection into treatment. In the language of causal path diagrams, an adjustment set is a set of variables that, when conditioned upon, closes all back door paths from the treatment to the outcome. We can condition on the adjustment set using a variety of alternative answer strategies, for example through regression adjustment, stratification, or matching.</p>
<p>The quality of causal inferences we draw comes down to whether our claims about selection into treatment are correct. If we’ve missed a cause (missed a back door path), then our inferences will be prone to bias. It is the nature of the selection-on-observables design that we can’t know if our claims about the processes that cause selection are correct or not; the design amounts to a leap of faith in the theoretical model.</p>
<p>The problems don’t end there. We risk bias if we fail to adjust for <span class="math inline">\(X\)</span> under some models — but we will also risk bias if we <em>do</em> adjust for <span class="math inline">\(X\)</span> under other models. In <a href="#fig-ch16num3">Figure&nbsp;<span>16.3</span></a> we illustrate four of the possible roles for an observable variable <span class="math inline">\(X\)</span>: as a confounder of the relationship between <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span>; as a collider, which is affected by both <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span>; as a mediator of the relationship between <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span>; and as a predictor of <span class="math inline">\(Y\)</span> with no connection to <span class="math inline">\(D\)</span>. We set aside in these DAGs the possible roles of an unobservable variable <span class="math inline">\(U\)</span> that would introduce additional problems of confounding.</p>
<div id="fig-ch16num3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-3.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.3: Four roles for an observable variable X.</figcaption></figure>
</div>
<p>If <span class="math inline">\(X\)</span> is a confounder, failing to adjust for it in studying the relationship between the treatment <span class="math inline">\(D\)</span> and outcome <span class="math inline">\(Y\)</span> will lead to confounding bias. We often think of fourth DAG as the alternative to this, where <span class="math inline">\(X\)</span> is a predictor of <span class="math inline">\(Y\)</span> but has no link to <span class="math inline">\(D\)</span>. In this circumstance, we still want to adjust for <span class="math inline">\(X\)</span> to seek efficiency improvements by soaking up additional variation in <span class="math inline">\(Y\)</span>, but failing to do so will not introduce bias. If the true model is definitely represented by either the first or fourth DAG, we should clearly choose to adjust for <span class="math inline">\(X\)</span>. In the first case, we should adjust to close the back-door path and in the fourth case, we will do no worse in terms of bias and may in fact increase precision.</p>
<p>However, the middle two DAGs present problems if we <em>do</em> adjust for <span class="math inline">\(X\)</span>. In the first, <span class="math inline">\(X\)</span> is a collider: it is affected by both <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span>. Adjusting for <span class="math inline">\(X\)</span> if this is the true model introduces collider bias, because we open a backdoor path between <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span> through <span class="math inline">\(X\)</span>. We also introduce bias if we control for <span class="math inline">\(X\)</span> if the mediator model (DAG 3) is the true model, wherein <span class="math inline">\(D\)</span> affects <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> affects <span class="math inline">\(Y\)</span> (i.e., <span class="math inline">\(X\)</span> is a mediator for the relationship between <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span>). But the reason here is different: controlling for a mediator adjusts away part of the true treatment effect.</p>
<p>In a selection-on-observables design, we must get many features of the model correct, not only about the factors that affect <span class="math inline">\(D\)</span>. We must be sure of all the arrows into <span class="math inline">\(X\)</span>, <span class="math inline">\(D\)</span>, and <span class="math inline">\(Y\)</span> and the order of the causal arrows. In some cases, in natural experiments where selection processes are not randomized by researchers but are nevertheless known, these assumptions can be sustained. In others, we will be making heroic assumptions.</p>
<p><a href="#def-ch16num2">Declaration&nbsp;<span>16.2</span></a> explores these considerations, with a model defining the relationship between a causal factor of interest <span class="math inline">\(D\)</span> and outcome <span class="math inline">\(Y\)</span> and an observable confounder <span class="math inline">\(X\)</span>, the average treatment effect as the inquiry, a simple measurement strategy, and two estimators with and without adjustment for <span class="math inline">\(X\)</span>. We use exact matching as our adjustment strategy.</p>
<div id="def-ch16num2" class="declaration theorem definition">
<p><span class="theorem-title"><strong>Declaration 16.2 </strong></span>Matching design declaration</p>
<div class="cell" data-file="scripts_declarations/declaration_16.2.R">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://kosukeimai.github.io/MatchIt/">MatchIt</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">exact_matching</span> <span class="op">&lt;-</span> </span>
<span>  <span class="kw">function</span><span class="op">(</span><span class="va">data</span><span class="op">)</span> <span class="op">{</span> </span>
<span>    <span class="va">matched</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://kosukeimai.github.io/MatchIt/reference/matchit.html">matchit</a></span><span class="op">(</span><span class="va">D</span> <span class="op">~</span> <span class="va">X</span>, method <span class="op">=</span> <span class="st">"exact"</span>, data <span class="op">=</span> <span class="va">data</span><span class="op">)</span> </span>
<span>    <span class="fu"><a href="https://kosukeimai.github.io/MatchIt/reference/match.data.html">match.data</a></span><span class="op">(</span><span class="va">matched</span><span class="op">)</span> </span>
<span>  <span class="op">}</span></span>
<span></span>
<span></span>
<span><span class="va">declaration_16.2</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">declare_model</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="fl">100</span>, </span>
<span>    U <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>, </span>
<span>    X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, prob <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span>,</span>
<span>    D <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, prob <span class="op">=</span> <span class="fl">0.25</span> <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> <span class="va">X</span><span class="op">)</span>,</span>
<span>    Y_D_0 <span class="op">=</span> <span class="fl">0.2</span> <span class="op">*</span> <span class="va">X</span> <span class="op">+</span> <span class="va">U</span>,</span>
<span>    Y_D_1 <span class="op">=</span> <span class="va">Y_D_0</span> <span class="op">+</span> <span class="fl">0.5</span></span>
<span>  <span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span>ATE <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Y_D_1</span> <span class="op">-</span> <span class="va">Y_D_0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_step</span><span class="op">(</span>handler <span class="op">=</span> <span class="va">exact_matching</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_measurement</span><span class="op">(</span>Y <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">D</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">D</span>,</span>
<span>                    weights <span class="op">=</span> <span class="va">weights</span>,</span>
<span>                    .method <span class="op">=</span> <span class="va">difference_in_means</span>,</span>
<span>                    label <span class="op">=</span> <span class="st">"Matched difference-in-means"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">D</span>, </span>
<span>                    .method <span class="op">=</span> <span class="va">difference_in_means</span>, </span>
<span>                    label <span class="op">=</span> <span class="st">"Raw difference-in-means"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>We declare beliefs about the selection process and how <span class="math inline">\(D\)</span>, <span class="math inline">\(Y\)</span>, and <span class="math inline">\(X\)</span> are related. The model needs to include potential outcomes for the main outcome of interest (<span class="math inline">\(Y\)</span>) and a specification of the assignment of the key causal variable (here, <span class="math inline">\(D\)</span>). Here, we have defined the assignment process as a function of an observable variable <span class="math inline">\(X\)</span>. In fact, <span class="math inline">\(X\)</span> is the only variable that affects selection into treatment: <span class="math inline">\(X\)</span> is a binary variable (i.e., two groups), and the probability of treatment is 0.4 when <span class="math inline">\(X=0\)</span> and 0.6 when <span class="math inline">\(X=1\)</span>. In addition, we define the potential outcomes for <span class="math inline">\(Y\)</span>, which invoke confounding by <span class="math inline">\(X\)</span> because it affects both <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span>. We only invoke one possible relationship between <span class="math inline">\(X\)</span>, <span class="math inline">\(Y\)</span>, and <span class="math inline">\(D\)</span>, and so do not consider the possibilities of colliders or mediators.</p>
<p>In our model, <span class="math inline">\(U\)</span> is not a confounder, because it affects <span class="math inline">\(Y\)</span> but not <span class="math inline">\(D\)</span>; this is a strong excludability assumption on which our causal inferences depend. The assumption is strong because ruling out all unobservable confounders is typically impossible. Most causal factors in nature are affected by many variables, only some of which we can imagine and measure. The first estimator, with adjustment, uses the weights from the exact matching estimator. The matching procedure adjusts for differences in the probability of selection into treatment according to <span class="math inline">\(X\)</span>. The second, unadjusted, estimator does not control for <span class="math inline">\(X\)</span> so suffers from unobserved confounding, because we do not adjust for <span class="math inline">\(X\)</span> which predicts both treatment and the outcome.</p>
<div id="lem-ch16num2" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 16.2 </strong></span>Matching design diagnosis</p>
<p>In <a href="#fig-ch16num4">Figure&nbsp;<span>16.4</span></a>, we see that the raw, unmatched estimate is quite biased (about 20% of the average estimate) and that the matched estimate is unbiased. If we fail to adjust for the observable features of the selection process, we have biased answers. But if we do control in this case, we obtain unbiased answers. However, as highlighted earlier, these results depend on the plausibility of our model, which in this case involves observed confounding of the relationship between <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span> by <span class="math inline">\(X\)</span>. If there was <em>unobservable</em> confounding from <span class="math inline">\(U\)</span>, or if <span class="math inline">\(X\)</span> was a collider or mediator, there would be bias even if we control for <span class="math inline">\(X\)</span>.</p>
<div id="fig-ch16num4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-4.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.4: Sampling distribution of two estimators.</figcaption></figure>
</div>
</div>
<section id="design-examples-1" class="level3" data-number="16.2.1"><h3 data-number="16.2.1" class="anchored" data-anchor-id="design-examples-1">
<span class="header-section-number">16.2.1</span> Design examples</h3>
<ul>
<li><p><span class="citation" data-cites="bateson_2012">Bateson (<a href="../references.html#ref-bateson_2012" role="doc-biblioref">2012</a>)</span> uses a selection-on-observables design to estimate the causal effect of crime victimization on political participation from regional barometer survey data. The main specification is justified by the argument that all back-door paths are closed using Ordinary Least Squares regression and a robustness check uses a nearest-neighbor matching approach under equivalent assumptions.</p></li>
<li><p><span class="citation" data-cites="Prillaman2022">Prillaman (<a href="../references.html#ref-Prillaman2022" role="doc-biblioref">2022</a>)</span> uses a matching design to compare Indian villages that featured women’s self-help groups to those that did not on rates of women’s political participation.</p></li>
</ul></section></section><section id="sec-ch16s3" class="level2" data-number="16.3"><h2 data-number="16.3" class="anchored" data-anchor-id="sec-ch16s3">
<span class="header-section-number">16.3</span> Difference-in-differences</h2>
<div class="ddbox">
<p>We declare a differences-in-differences design in which the effect of a treatment is assessed by comparing changes over time for a unit that gets treated to changes over time in the same period for a unit the does not get treated. The declaration and diagnosis helps clarify when effect heterogeneity threatens causal inferences drawn from this design.</p>
</div>
<p>The difference-in-differences design compares the pre-to-post-treatment difference in treated units to that of untreated units. We use the over-time change in the untreated units to account for the changes over time in the treated units that are not due to the treatment. Suppose outcomes were rising over time for all units but we only looked at the pre-to-post difference in the treatment group. We might falsely infer the treatment increased outcomes. The logic of the difference-in-differences design is that we can subtract off the trends affecting all units in order to adjust our causal effect estimates.</p>
<p>The difference-in-differences design relies on a strong assumption in <span class="math inline">\(M\)</span>: the parallel trends assumption. This assumption asserts that the <em>changes</em> (not the levels) in untreated potential outcomes are the same for treated and untreated units. Because this assumption depends on the values of the unrealized (and thus unobservable) control potential outcomes in the treated units after treatment, it cannot be tested. A widely-used diagnostic is to look at the trends in outcomes between the treated and control unit <em>before</em> treatment; this is only an indirect test because the parallel trends assumption concerns the unobserved control trend of the actually treated unit.</p>
<p>The design has been famously used for analyses of two periods (before and after) and two groups (treated and untreated) such as a policy change in one state compared to another before and after the policy change. Today, difference-in-differences is most often used in many-period many-group settings with observational panel data. Here, the logic of the two-period two-group design is extended through analogy. Parallel trends between treated and control groups are assumed <em>on average</em> across treated groups and periods. Unfortunately, the analogy holds only under limited circumstances, a fact only recently discovered.</p>
<p><a href="#def-ch16num3">Declaration&nbsp;<span>16.3</span></a> describes a 20-period, 20-unit design in which eventually-treated units become treated at different times, a common setting in empirical social science often referred to as the staggered adoption design. The treatment effect of interest might be a state-level policy adopted in 20 states at some point within a 20-year period, so we draw on comparisons before and after policy adoption within states and comparisons across states that have and have not yet adopted treatment. We use the <code>did_multiplegt_tidy</code> function (available in the <code>rdss</code> companion package) to prepare the output from the <code>DIDmultiplegt</code> package that implements the estimation procedure.</p>
<div id="def-ch16num3" class="declaration theorem definition">
<p><span class="theorem-title"><strong>Declaration 16.3 </strong></span>Difference-in-differences design</p>
<div class="cell" data-file="scripts_declarations/declaration_16.3.R">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">rdss</span><span class="op">)</span> <span class="co"># for helper functions</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">DIDmultiplegt</span><span class="op">)</span></span>
<span></span>
<span><span class="va">N_units</span> <span class="op">&lt;-</span> <span class="fl">20</span></span>
<span><span class="va">N_time_periods</span> <span class="op">&lt;-</span> <span class="fl">20</span></span>
<span></span>
<span><span class="va">declaration_16.3</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu">declare_model</span><span class="op">(</span></span>
<span>  units <span class="op">=</span> <span class="fu">add_level</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="va">N_units</span>, </span>
<span>    U_unit <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>, </span>
<span>    D_unit <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">U_unit</span> <span class="op">&gt;</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">U_unit</span><span class="op">)</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span>,</span>
<span>    D_time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">N_time_periods</span>, <span class="va">N</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="op">)</span>,</span>
<span>  periods <span class="op">=</span> <span class="fu">add_level</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="va">N_time_periods</span>,</span>
<span>    U_time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,</span>
<span>    nest <span class="op">=</span> <span class="cn">FALSE</span></span>
<span>  <span class="op">)</span>,</span>
<span>  unit_period <span class="op">=</span> <span class="fu">cross_levels</span><span class="op">(</span></span>
<span>    by <span class="op">=</span> <span class="fu">join_using</span><span class="op">(</span><span class="va">units</span>, <span class="va">periods</span><span class="op">)</span>, </span>
<span>    U <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,</span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">U</span> <span class="op">+</span> <span class="va">U_unit</span> <span class="op">+</span> <span class="va">U_time</span> <span class="op">+</span> </span>
<span>                         <span class="va">D</span> <span class="op">*</span> <span class="op">(</span><span class="fl">0.2</span> <span class="op">-</span> <span class="fl">1</span> <span class="op">*</span> <span class="op">(</span><span class="va">D_time</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">periods</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, </span>
<span>                       conditions <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>D <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    D <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">D_unit</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">&amp;</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">periods</span><span class="op">)</span> <span class="op">&gt;=</span> <span class="va">D_time</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span>,</span>
<span>    D_lag <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/rdss/man/lag_by_group.html">lag_by_group</a></span><span class="op">(</span><span class="va">D</span>, groups <span class="op">=</span> <span class="va">units</span>, n <span class="op">=</span> <span class="fl">1</span>, order_by <span class="op">=</span> <span class="va">periods</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span></span>
<span>    ATT <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Y_D_1</span> <span class="op">-</span> <span class="va">Y_D_0</span><span class="op">)</span>, </span>
<span>    subset <span class="op">=</span> <span class="va">D</span> <span class="op">==</span> <span class="fl">1</span></span>
<span>  <span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span></span>
<span>    ATT_switchers <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Y_D_1</span> <span class="op">-</span> <span class="va">Y_D_0</span><span class="op">)</span>, </span>
<span>    subset <span class="op">=</span> <span class="va">D</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">&amp;</span> <span class="va">D_lag</span> <span class="op">==</span> <span class="fl">0</span> <span class="op">&amp;</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">D_lag</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_measurement</span><span class="op">(</span>Y <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">D</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span></span>
<span>    <span class="va">Y</span> <span class="op">~</span> <span class="va">D</span>, fixed_effects <span class="op">=</span> <span class="op">~</span> <span class="va">units</span> <span class="op">+</span> <span class="va">periods</span>,</span>
<span>    .method <span class="op">=</span> <span class="va">lm_robust</span>,</span>
<span>    inquiry <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ATT"</span>, <span class="st">"ATT_switchers"</span><span class="op">)</span>,</span>
<span>    label <span class="op">=</span> <span class="st">"twoway-fe"</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span></span>
<span>    Y <span class="op">=</span> <span class="st">"Y"</span>, </span>
<span>    G <span class="op">=</span> <span class="st">"units"</span>, </span>
<span>    T <span class="op">=</span> <span class="st">"periods"</span>, </span>
<span>    D <span class="op">=</span> <span class="st">"D"</span>,</span>
<span>    handler <span class="op">=</span> <span class="fu">label_estimator</span><span class="op">(</span><span class="va">did_multiplegt_tidy</span><span class="op">)</span>,</span>
<span>    inquiry <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"ATT"</span>, <span class="st">"ATT_switchers"</span><span class="op">)</span>,</span>
<span>    label <span class="op">=</span> <span class="st">"chaisemartin"</span></span>
<span>  <span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>We define hierarchical data with time periods nested within groups, such that each of the 20 units have 20 time periods from 1 to 20. We assign units to be treated at some point in the period (<code>D_unit</code>), and confound treatment assignment with unobservable unit-specific features <code>U_unit</code>. (If there were no confounding, we would not need the parallel pretrends assumption.) In addition, the timing of treatment is randomly assigned (<code>D_time</code>). The assignment <code>D</code> then is jointly determined by whether the unit is treated and whether the current period is after the assigned <code>D_time</code>. We allow for unit-specific variation <code>U_unit</code> and time-specific variation <code>U_time</code> that affects the outcome as well as unit-period characteristics <code>U</code>. Potential outcomes are a function of these unit-, time-, and unit-time-specific characteristics, and a treatment effect that varies according to when units are treated (more on the importance of this treatment effect heterogeneity below).</p>
<p>The difference-in-difference design typically targets the average treatment effect on the treated (ATT) inquiry. We leverage over time comparisons within units to isolate the causal effect of treatment, and difference out time-varying characteristics by subtracting off the change in untreated units. Unfortunately, except under extremely limited circumstances — exactly homogeneous treatment effects — we will not be able to recover unbiased estimates of the ATT. We can, however, under some circumstances and with some estimators, recover the ATT for a specific subgroup: units in those periods that just switched from untreated to treated. We declare the ATT for these “switchers” as the inquiry.</p>
<p>So many answer strategies have been proposed in recent years to address bias in the difference-in-differences design that we cannot summarize them in this short entry. Instead, we illustrate how to assess the properties of two particular estimators under a range of conditions. First, we define the standard two-way fixed effects estimator with fixed effects by time and unit. The two-way fixed effects fits the empirical goal of difference-in-differences: the time fixed effects net out time-varying unit-invariant variables such as seasonality and time trends. The unit fixed effects net out unit-varying variables that are time-invariant like race or age-at-birth of individuals and long-term histories of violence of territories. However, the two-way fixed effects estimator relies on comparisons between units that are treated and units that are <em>not yet</em> treated. When treatment effects differ across units depending on when they are treated (as they do in the design here), then those comparisons will be biased: part of the treatment effect will be subtracted out of the estimate. Our second estimator, proposed by <span class="citation" data-cites="chaisemartin">Chaisemartin and d’Haultfoeuille (<a href="../references.html#ref-chaisemartin" role="doc-biblioref">2020</a>)</span>, addresses this problem when estimating the ATT among switchers.</p>
<div id="lem-ch16num3" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 16.3 </strong></span>Difference-in-Differences diagnosis</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">diagnosis_16.3</span> <span class="op">&lt;-</span> <span class="fu">diagnose_design</span><span class="op">(</span><span class="va">declaration_16.3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-ch16num5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-5.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.5: Sampling distributions of two difference-in-differences estimators.</figcaption></figure>
</div>
<p><a href="#fig-ch16num5">Figure&nbsp;<span>16.5</span></a> shows that the two-way fixed effects estimator is biased for both the ATT and the ATT on the switchers. By contrast, the <span class="citation" data-cites="chaisemartin">Chaisemartin and d’Haultfoeuille (<a href="../references.html#ref-chaisemartin" role="doc-biblioref">2020</a>)</span> estimator is unbiased for the ATT on the switchers. Neither estimator recovers unbiased estimates of the ATT. The next section explains why.</p>
</div>
<div id="lem-ch16num4" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 16.4 </strong></span>Redesigning over alternative models of treatment effect heterogeneity</p>
<p>The issues with the two-way fixed effects estimator emerge when treatment effects differ for units that are treated later versus earlier. Following <a href="../introduction/research-design-principles.html#exm-designagnostically">Principle&nbsp;<span>3.2</span></a>: Design agnostically, we declare a model with homogeneous treatment effects, as well as two kinds of time-varying heterogeneous treatment effects: one in which effects are lower for units treated later and one in which effects are higher for units treated later.</p>
<p>The timing of treatment, nature of heterogeneous effects, and answer strategies interact to determine the properties of the design. <a href="#fig-ch16num6">Figure&nbsp;<span>16.6</span></a> shows the diagnosis under all three sets of potential outcomes, and examines both the ATT and the ATT for switchers inquiries. We consider both the two-way fixed effects estimator and the <span class="citation" data-cites="chaisemartin">Chaisemartin and d’Haultfoeuille (<a href="../references.html#ref-chaisemartin" role="doc-biblioref">2020</a>)</span> estimator.</p>
<p>When treatment effects happen to be homogeneous (middle panel), both estimators recover unbiased estimates of both the ATT and the ATT for switchers, which of course are equal to one another because of treatment effect homogeneity. However, when treatment effects vary with the timing of treatment (left or right panels), the two-way fixed-effects estimator is biased for both inquiries. The <span class="citation" data-cites="chaisemartin">Chaisemartin and d’Haultfoeuille (<a href="../references.html#ref-chaisemartin" role="doc-biblioref">2020</a>)</span> estimator is also biased for the ATT, but remains unbiased for the ATT among switchers regardless of the pattern of treatment effect heterogeneity.</p>
<div id="fig-ch16num6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-6.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.6: Diagnoses of two generalized difference-in-differences estimators under three types of potential outcomes.</figcaption></figure>
</div>
</div>
<section id="design-examples-2" class="level3" data-number="16.3.1"><h3 data-number="16.3.1" class="anchored" data-anchor-id="design-examples-2">
<span class="header-section-number">16.3.1</span> Design examples</h3>
<ul>
<li><p><span class="citation" data-cites="paglayan2019public">Paglayan (<a href="../references.html#ref-paglayan2019public" role="doc-biblioref">2019</a>)</span> uses a difference-in-differences design to estimate the causal effect of collective bargaining rights for teachers on education spending in the American states.</p></li>
<li><p><span class="citation" data-cites="Carreri2017">Carreri and Dube (<a href="../references.html#ref-Carreri2017" role="doc-biblioref">2017</a>)</span> uses a difference-in-differences design to estimate the effect of changes in the international price of oil on the election of right-wing politicians in oil-dependent countries.</p></li>
</ul></section></section><section id="sec-ch16s4" class="level2" data-number="16.4"><h2 data-number="16.4" class="anchored" data-anchor-id="sec-ch16s4">
<span class="header-section-number">16.4</span> Instrumental variables</h2>
<div class="ddbox">
<p>We declare a design in which a researcher addresses confounding concerns by using an instrumental variable. Under the right conditions, the approach can generate unbiased estimates for treatment effects for units whose treatment status is sensitive to the instrument.</p>
</div>
<p>When we cannot credibly assert that we have controlled for all confounding variables as in a selection-on-observables design (see <a href="#sec-ch16s2"><span>Section&nbsp;16.2</span></a>) and when we do not think the parallel trends assumption is likely to hold in a difference-in-differences design (see <a href="#sec-ch16s3"><span>Section&nbsp;16.3</span></a>), we might have to give up on our goal of drawing causal inferences.</p>
<p>But occasionally, the world yields an opportunity to sidestep unobserved confounding by generating as-if random variation in a variable that itself affects the treatment variable but does not directly affect the outcome. We call the variable that is as-if randomly assigned by the world an “instrument.”</p>
<p>Instruments are special. They are variables that are randomly assigned by nature, the government, or other individuals or groups. Usually, genuine random assignments have to be crafted by researchers as part of a deliberate data strategy. Experimenters go to great lengths to randomly expose some units but not others to treatments. When the world provides bona fide random variation in an instrumental variable, it’s a rare and valuable opportunity. By virtue of as-if random assignment, we can learn about the average causal effects of the instrument itself without any further consternation. Conditional on geography and season, weather conditions are as-if randomly assigned, so we can learn about the average effects of rainfall on many outcomes, like crop yields, voter turnout, and attendance at sporting events. Conditional on gender and birth year, draft numbers are randomly assigned by the government, so we can learn about the average effects of being drafted on educational attainment, future earnings, or public policy preferences.</p>
<p>We illustrate the logic of instrumental variables with the DAG shown in <a href="#fig-ch16num7">Figure&nbsp;<span>16.7</span></a>. An instrument <span class="math inline">\(Z\)</span> affects an endogenous treatment <span class="math inline">\(D\)</span> which subsequently affects an outcome <span class="math inline">\(Y\)</span>. Many other common causes, summarized in terms of unknown heterogeneity <span class="math inline">\(U\)</span>, affect both <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span>. It is because of this unmeasured confounding that we cannot learn about the effect of <span class="math inline">\(D\)</span> on <span class="math inline">\(Y\)</span> directly using standard tools.</p>
<div id="fig-ch16num7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-7.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.7: Directed acyclic graph of an instrumental variables design.</figcaption></figure>
</div>
<p>We can naturally imagine an inquiry that represents the effect of the instrument (<span class="math inline">\(Z\)</span>) on an outcome of interest such as the effect of the draft number on future earnings. In the terminology of instrumental variables, this inquiry is called the “reduced form” or the “intention-to-treat” (ITT) effect. If it’s really true that the instrument is randomly assigned by the world, estimation of the reduced form effect is straightforward: we estimate the causal effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(Y\)</span> using, for example, a difference-in-means estimator. Sometimes, we are also interested in the “first-stage” effect of the instrument on the treatment variable. Similarly, we can target this inquiry by studying the causal effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(D\)</span>, for example using the difference-in-means estimator again.</p>
<p>The trouble comes when we want to leverage the random assignment of the instrument (<span class="math inline">\(Z\)</span>) to learn about the average causal effect of the treatment variable (<span class="math inline">\(D\)</span>) on the outcome (<span class="math inline">\(Y\)</span>), where <span class="math inline">\(D\)</span> is not randomly assigned but rather affected by <span class="math inline">\(Z\)</span> and also other variables. To do so, we need to understand better how the instrument affects whether units are <em>treated</em> and then how both affect the outcome of interest. We need to understand “compliance” with the instrument.</p>
<p>We can define the compliance types of units in terms of the combinations of values the potential outcomes of <span class="math inline">\(D\)</span> take on as a function of the values of the instrument <span class="math inline">\(Z\)</span>. The combinations are made up of the value of the treatment if unit <span class="math inline">\(i\)</span> is assigned to control (<span class="math inline">\(D_i(Z_i = 0)\)</span>) and the value if it is assigned to treatment (<span class="math inline">\(D_i(Z_i = 1)\)</span>). With a binary instrument and binary treatment, there are four possible potential outcomes values and thus four types, enumerated in <a href="#tbl-compliancetypes">Table&nbsp;<span>16.2</span></a>. These compliance types are sometimes known as “principal strata” <span class="citation" data-cites="frangakis2002principal">(<a href="../references.html#ref-frangakis2002principal" role="doc-biblioref">Frangakis and Rubin 2002</a>)</span>.</p>
<div id="tbl-compliancetypes" class="anchored">
<table class="table">
<caption>Table&nbsp;16.2: Compliance types</caption>
<thead><tr class="header">
<th>Type</th>
<th><span class="math inline">\(D_i(Z_i = 0)\)</span></th>
<th><span class="math inline">\(D_i(Z_i = 1)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Never-taker</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Complier</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Defier</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>Always-taker</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
<p>Never-takers are those who never take the treatment, no matter what the value of the instrument. Compliers take the value of the treatment they are assigned by the instrument. Defiers do exactly the opposite. When the instrument assigns them to take the treatment, defiers refuse it, but if it assigns them not to, they do take treatment. Like their name suggests, always-takers take the treatment regardless of the value of the instrument.</p>
<p>With these types in mind, we can now define a new inquiry that we will be able to target with instrumental variables under a special set of assumptions: a “local” average treatment effect (LATE) among compliers. The “local” qualifier indicates that the effect applies only to the specific group of units whose treatment status changes as a result of the instrument. The LATE is <span class="math inline">\(\mathbb{E}[Y_i(D_i = 1) - Y_i(D_i = 0) | D_i(Z_i = 1) &gt; D_i(Z_i = 0)]\)</span>. This quantity is the average treatment effect among the compliers. The LATE is different from the ATE because it does not average over the effects for never-takers, always-takers, and defiers, but the ATE does.</p>
<p>We can adopt an instrumental variables answer strategy — using two-stage least squares for example — to estimate the LATE. But to do so without bias, we need to invoke new assumptions on top of those for randomized experiments. In the case of a binary instrument and a binary treatment, the five assumptions are:</p>
<ol type="1">
<li><p>Exogeneity of the instrument: <span class="math inline">\(Y_i(D_i = 1), Y_i(D_i = 0), D_i(Z_i = 1), D_i(Z_i = 0) \indep Z_i | X_i\)</span>. Substantively, this assumption requires that (possibly conditional on observed covariates in <span class="math inline">\(X\)</span>) the instrument is as-if randomly assigned, so it is jointly independent of the treated and untreated potential outcomes as well as the potential values the treatment variable <span class="math inline">\(D\)</span> would take on depending on the values of the instrument <span class="math inline">\(Z\)</span>. Exogeneity is usually justified on the basis of qualitative knowledge about why as-if random assignment is a reasonable assumption to make. The assumption can be bolstered — but not directly tested — with design checks like whether pre-treatment values of the covariates are balanced across the levels of the instrument.</p></li>
<li><p>Excludability of the instrument: <span class="math inline">\(Y_i(D_i(Z_i), Z_i) = Y_i(D_i(Z_i))\)</span>. We can “exclude” the instrument from the potential outcomes function <span class="math inline">\(Y_i()\)</span>, so the only relevant argument is the value of the treatment variable. Substantively, this means that <span class="math inline">\(Z\)</span> has exactly no effect on <span class="math inline">\(Y\)</span> except by changing the value of <span class="math inline">\(D\)</span>, or in other words a “total mediation assumption.” Under the exclusion restriction, the effect of the instrumental variable is wholly mediated by the treatment variable. The validity of the exclusion restriction cannot be demonstrated empirically and typically must be asserted on qualitative grounds. Since the reduced form of the instrument can be estimated for many different outcome variables, one piece of evidence that can bolster the exclusion restriction is to show that the instrument does not affect other plausible causal precedents of the outcome variable. If it does affect other variables that might, in turn, affect the outcome, the exclusion restriction might be an implausible assumption.</p></li>
<li><p>Non-interference: <span class="math inline">\(Y(D_i(Z_i), D_{-i}, Z_{-i}) = Y(D_i(Z_i))\)</span>. Like any non-interference assumption, here we assert that for any particular unit, other units’ values of the instrument or the treatment do not affect the outcome.</p></li>
<li><p>Monotonicity: <span class="math inline">\(D_i(Z_i = 1) \geq D_i(Z_i = 0), \forall_i\)</span>. This assumption states that the effect of the instrument on the treatment is either zero or is positive for all units. Monotonicity rules out defiers. Monotonicity is usually quite plausible (it’s tough to imagine a person who <em>would</em> serve in the military if not drafted but <em>would not</em> serve if drafted!), but it’s not possible to affirm empirically. An empirical test that demonstrates a positive effect of the instrument on the treatment for one group but a negative effect for a different group could, however, falsify the monotonicity assumption.</p></li>
<li><p>Non-zero effect of the instrument on the treatment. If the instrument does not affect the treatment, then it is useless for learning about the effects of the treatment on the outcome, simply because it generates no compliers. If there are no compliers, the LATE itself is undefined.</p></li>
</ol>
<p>If all five of these assumptions are met, it can be shown that the inquiry <span class="math inline">\(\mathrm{LATE} = \frac{\mathrm{ATE}_{ \mathrm{Z\rightarrow Y} }}{\mathrm{ATE}_{Z\rightarrow D}} = \frac{\mathrm{Reduced~Form}}{\mathrm{First~Stage}}\)</span>. It is the quotient of the ATE of the instrument on the outcome divided by the ATE of the instrument on the treatment. This expression underlines the importance of the fifth assumption: if the instrument doesn’t affect the treatment, the first stage is equal to zero and the ratio is undefined.</p>
<p>Many of the five assumptions are represented in the DAG in <a href="#fig-ch16num7">Figure&nbsp;<span>16.7</span></a>. The exogeneity of the instrument is represented by the exclusion of a causal effect of <span class="math inline">\(U\)</span> on <span class="math inline">\(Z\)</span>. The omission of an arrow from <span class="math inline">\(Z\)</span> to <span class="math inline">\(Y\)</span> directly invokes the exclusion restriction. Non-interference is typically not directly represented in DAGs. Monotonicity and the non zero effect of the instrument on the treatment is represented by the causal arrow from <span class="math inline">\(Z\)</span> to <span class="math inline">\(D\)</span>.</p>
<p>Moving to the answer strategy, a plug-in estimator of the LATE is the difference-in-means of the outcome according to the instrument divided by the difference-in-means of the treatment according to the instrument. Equivalently, we can use two-stage least squares, which will yield the identical answer as the ratio of the difference-in-means estimates when no covariates are included in the regression.</p>
<p>With the four elements of the design in hand, we declare the model in code, invoking each of the five assumptions in doing so:</p>
<div id="def-ch16num4" class="declaration theorem definition">
<p><span class="theorem-title"><strong>Declaration 16.4 </strong></span>Instrumental variables design</p>
<div class="cell" data-file="scripts_declarations/declaration_16.4.R">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">declaration_16.4</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">declare_model</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="fl">100</span>, </span>
<span>    U <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,</span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">D</span> <span class="op">~</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">Z</span> <span class="op">+</span> <span class="va">U</span> <span class="op">&gt;</span> <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span>, </span>
<span>                       conditions <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>Z <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, </span>
<span>    <span class="fu">potential_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="fl">0.1</span> <span class="op">*</span> <span class="va">D</span> <span class="op">+</span> <span class="fl">0.25</span> <span class="op">+</span> <span class="va">U</span>, </span>
<span>                       conditions <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>D <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    complier <span class="op">=</span> <span class="va">D_Z_1</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">&amp;</span> <span class="va">D_Z_0</span> <span class="op">==</span> <span class="fl">0</span></span>
<span>  <span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span>LATE <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Y_D_1</span> <span class="op">-</span> <span class="va">Y_D_0</span><span class="op">)</span>, subset <span class="op">=</span> <span class="va">complier</span> <span class="op">==</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">declare_assignment</span><span class="op">(</span>Z <span class="op">=</span> <span class="fu">complete_ra</span><span class="op">(</span><span class="va">N</span>, prob <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_measurement</span><span class="op">(</span>D <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">D</span> <span class="op">~</span> <span class="va">Z</span><span class="op">)</span>,</span>
<span>                      Y <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">D</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">D</span> <span class="op">|</span> <span class="va">Z</span>, .method <span class="op">=</span> <span class="va">iv_robust</span>, inquiry <span class="op">=</span> <span class="st">"LATE"</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>The exclusion restriction is invoked in omitting a causal direct effect of <span class="math inline">\(Z\)</span> in the <span class="math inline">\(Y\)</span> potential outcomes. We invoke the monotonicity and non-zero effect of <span class="math inline">\(Z\)</span> on <span class="math inline">\(D\)</span> in the <span class="math inline">\(D\)</span> potential outcomes, which have an effect of <span class="math inline">\(Z\)</span> of 1. We invoke the non-interference assumption by excluding effects of the instrument values from other units in the definition of the <span class="math inline">\(D\)</span> and <span class="math inline">\(Y\)</span> potential outcomes. And we invoke the ignorability of <span class="math inline">\(Z\)</span> by randomly assigning it in the assignment step.</p>
<p>How can you use this declaration? Many instrumental variables designs involve historical data, such that most remaining design choices are in the answer strategy. Declaring and diagnosing the design can yield insights about how to construct standard errors and confidence intervals and the implications of analysis procedures in which data-dependent tests are run before fitting instrumental variables models — and only fit if the tests pass. But other instrumental variables papers involve prospective data collection, in which an instrument is identified and outcome data (and possibly instrument and treatment data) are collected anew. In such settings, the design diagnosis and redesign tools are just as useful as in any prospective research design: to help select sampling and measurement procedures from the sample size to the number of outcomes to be collected. The key in this case is to build in the features of the instrument, the potential outcomes of treatment receipt, and the potential outcomes of the ultimate outcome of interest and to explore violations of the five assumptions in the model.</p>
<section id="design-examples-3" class="level3" data-number="16.4.1"><h3 data-number="16.4.1" class="anchored" data-anchor-id="design-examples-3">
<span class="header-section-number">16.4.1</span> Design examples</h3>
<ul>
<li><p><span class="citation" data-cites="nellis_siddiqui_2018">Nellis and Siddiqui (<a href="../references.html#ref-nellis_siddiqui_2018" role="doc-biblioref">2018</a>)</span> instrument for the share of secular legislators with the as-if randomly assigned victory of secularist candidates in close elections. The authors use this instrument to study the causal effect of secular legislators on religious violence in Pakistan.</p></li>
<li><p><span class="citation" data-cites="Stokes2016">Stokes (<a href="../references.html#ref-Stokes2016" role="doc-biblioref">2016</a>)</span> studies the causal effects of wind turbines on voting for incumbents, instrumenting for the presence or absence of wind turbines with plausibly exogeneous differences in wind speeds across localities.</p></li>
</ul></section></section><section id="sec-ch16s5" class="level2" data-number="16.5"><h2 data-number="16.5" class="anchored" data-anchor-id="sec-ch16s5">
<span class="header-section-number">16.5</span> Regression discontinuity designs</h2>
<div class="ddbox">
<p>We declare a design in which the assignment of a treatment is determined by whether a characteristic of a unit exceeds a certain threshold value. We demonstrate through diagnosis the bias-variance tradeoff at the heart of the choice of answer strategies that target the local average treatment effect inquiry, defined right at the cutoff.</p>
</div>
<p>Regression discontinuity designs exploit substantive knowledge that treatment is assigned in a particular way: everyone above a threshold is assigned to treatment and everyone below it is not. Even though researchers do not control the assignment, substantive knowledge about the threshold serves as a basis for a strong causal identification claim.</p>
<p>Thistlewhite and Campbell introduced the regression discontinuity design in the 1960s to study the impact of scholarships on academic success <span class="citation" data-cites="thistlethwaite1960regression">(<a href="../references.html#ref-thistlethwaite1960regression" role="doc-biblioref">Thistlethwaite and Campbell 1960</a>)</span>. Their insight was that students with a test score just above a scholarship cutoff were plausibly comparable to students whose scores were just below the cutoff, so any differences in future academic success could be attributed to the scholarship itself.</p>
<p>Just like instrumental variables, regression discontinuity designs identify a local average treatment effect: in this case, the average effect of treatment local to the cutoff. The main trouble with the design is the vanishing amount of data available as we approach the cutoff, so any answer strategy needs to use data that is some distance away from the cutoff. The further away from the cutoff we move, the larger the threat of bias because units become less and less similar.</p>
<p>Regression discontinuity designs have four components: a running variable <span class="math inline">\(X\)</span>, a cutoff, a treatment variable <span class="math inline">\(D\)</span>, and an outcome <span class="math inline">\(Y\)</span>. The cutoff determines which units are treated depending on the value of the running variable. The running variable might be the Democratic party’s margin of victory at time <span class="math inline">\(t-1\)</span>, and the treatment <span class="math inline">\(D\)</span> might be whether the Democratic party won the election in time <span class="math inline">\(t-1\)</span>. The outcome <span class="math inline">\(Y\)</span> might be the Democratic vote margin at time <span class="math inline">\(t\)</span>.</p>
<p>A major assumption required for the regression discontinuity design is that the conditional expectation functions — functions that define the expected value of the outcome at every level of the running variable — for both treatment and control potential outcomes are continuous at the cutoff.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>The regression discontinuity design is closely related to the selection-on-observables design in that exact knowledge of the assignment mechanism is needed. In <a href="#fig-ch16num8">Figure&nbsp;<span>16.8</span></a>, we illustrate the DAG for the RD design, which includes a treatment with a known assignment mechanism (that units with <span class="math inline">\(X&gt;\mathrm{cutoff}\)</span> are treated and those below are not). The running variable <span class="math inline">\(X\)</span>, is a common cause both of treatment and the outcome, and so must be adjusted for (indicated by the dashed box) in order to identify the effect of treatment on the outcome and avoid confounding bias.</p>
<div id="fig-ch16num8" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-8.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.8: Directed acyclic graph for the regression discontinuity design.</figcaption></figure>
</div>
<p><a href="#fig-ch16num9">Figure&nbsp;<span>16.9</span></a> illustrates the major features of the model for the regression discontinuity using simulated data. The untreated units (blue points) are plotted to the left of the cutoff (vertical line), and the treated units (red points) are plotted to the right. The true conditional expectation functions for both the treated and untreated potential outcomes are displayed as colored lines, dashed where they are unobservable and solid where they are observable.</p>
<div id="fig-ch16num9" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-9.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.9: Data from a regression discontinuity design. On the x-axis is the running variable, which defines the cut off between control (here, below 0 on the running variable) and treatment (above 0). The outcome Y is on the y-axis. We illustrate smooth potential outcomes by showing the observed data curve (solid) and the counterfactual potential outcome (dashed).</figcaption></figure>
</div>
<p>The inquiry in a regression discontinuity design is the effect of the treatment exactly at the cutoff. Formally, it is the difference in the conditional expectation functions of the control and treatment potential outcomes when the running variable is exactly zero. The black vertical line in the plot shows this difference.</p>
<p>The data strategy is to collect the outcome data for all units within a interval (bandwidth) around the cutoff. The choice of bandwidth involves a tradeoff between bias and variance. The wider we make the bandwidth, the more data we have, and thus the more precision we may be able to achieve. However, the claim of causal identification comes from the comparability of units <em>just</em> above and <em>just</em> below the threshold. Units far from the cutoff are not likely to be comparable: at a minimum they differ in their values of the running variable and if that is correlated with other unobserved heterogeneity then they may differ in that too. Thus, the more units we compare further from the threshold, the more likely we are to induce bias in our estimates of the treatment effect. The ultimate bandwidth chosen for analysis is a function of the data collected in the data strategy and the bandwidth chosen in the answer strategy, which is often the output of an automated process.</p>
<div id="def-ch16num5" class="declaration theorem definition">
<p><span class="theorem-title"><strong>Declaration 16.5 </strong></span>Regression discontinuity design</p>
<div class="cell" data-file="scripts_declarations/declaration_16.5.R">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">rdss</span><span class="op">)</span> <span class="co"># for helper functions</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">rdrobust</span><span class="op">)</span></span>
<span></span>
<span><span class="va">cutoff</span> <span class="op">&lt;-</span> <span class="fl">0.5</span></span>
<span><span class="va">control</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/vector.html">as.vector</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/poly.html">poly</a></span><span class="op">(</span><span class="va">X</span>, <span class="fl">4</span>, raw <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.7</span>, <span class="op">-</span><span class="fl">.8</span>, <span class="fl">.5</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">}</span></span>
<span><span class="va">treatment</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/vector.html">as.vector</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/poly.html">poly</a></span><span class="op">(</span><span class="va">X</span>, <span class="fl">4</span>, raw <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="op">-</span><span class="fl">1.5</span>, <span class="fl">.5</span>, <span class="fl">.8</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fl">.15</span><span class="op">}</span></span>
<span></span>
<span><span class="va">declaration_16.5</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">declare_model</span><span class="op">(</span></span>
<span>    N <span class="op">=</span> <span class="fl">500</span>,</span>
<span>    U <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">0</span>, <span class="fl">0.1</span><span class="op">)</span>,</span>
<span>    X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span> <span class="op">+</span> <span class="va">U</span> <span class="op">-</span> <span class="va">cutoff</span>,</span>
<span>    D <span class="op">=</span> <span class="fl">1</span> <span class="op">*</span> <span class="op">(</span><span class="va">X</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>    Y_D_0 <span class="op">=</span> <span class="fu">control</span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">+</span> <span class="va">U</span>,</span>
<span>    Y_D_1 <span class="op">=</span> <span class="fu">treatment</span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">+</span> <span class="va">U</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_inquiry</span><span class="op">(</span>LATE <span class="op">=</span> <span class="fu">treatment</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span> <span class="op">-</span> <span class="fu">control</span><span class="op">(</span><span class="fl">0.5</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">declare_measurement</span><span class="op">(</span>Y <span class="op">=</span> <span class="fu">reveal_outcomes</span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">D</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span></span>
<span>    <span class="va">Y</span>, <span class="va">X</span>, c <span class="op">=</span> <span class="fl">0</span>, </span>
<span>    term <span class="op">=</span> <span class="st">"Bias-Corrected"</span>,</span>
<span>    .method <span class="op">=</span> <span class="va">rdrobust_helper</span>,</span>
<span>    inquiry <span class="op">=</span> <span class="st">"LATE"</span>,</span>
<span>    label <span class="op">=</span> <span class="st">"optimal"</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>Regression discontinuity answer strategies approximate the treated and untreated conditional expectation functions to the left and right of the cutoff. The choice of answer strategy involves two key choices: the bandwidth of data around the threshold that is used for estimation, and the model used to fit that data. We declare the local polynomial regression discontinuity estimator with the robust bias-corrected inference procedures described in <span class="citation" data-cites="calonico2014robust">Calonico, Cattaneo, and Titiunik (<a href="../references.html#ref-calonico2014robust" role="doc-biblioref">2014</a>)</span>, which fits a nonparametric model to the data and chooses an optimal bandwidth that minimizes bias. This robust estimator is now widely used in practice, because it navigates the bias-variance tradeoff in selecting bandwidths and statistical model specifications in a data-driven manner. The procedure also obviates the need for researchers to select these parameters themselves.</p>
<p><a href="#fig-ch16num10">Figure&nbsp;<span>16.10</span></a> illustrates the tradeoff in bandwidth selection for a one-degree polynomial (linear interaction). We see the bias-variance tradeoff directly. The bias increases the wider the bandwidth and the more we are relying on data further from the threshold whereas the variance (here, the standard deviation of the estimates) is decreasing the more data we add by widening the bandwidth.</p>
<div id="def-ch16num6" class="declaration theorem definition">
<p><span class="theorem-title"><strong>Declaration 16.6 </strong></span>Regression discontinuity designs with varying bandwidths</p>
<div class="cell" data-file="scripts_declarations/declaration_16.6.R">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">declaration_16.6</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">declaration_16.5</span> <span class="op">+</span> </span>
<span>  <span class="fu">declare_estimator</span><span class="op">(</span></span>
<span>    <span class="va">Y</span> <span class="op">~</span> <span class="va">X</span> <span class="op">*</span> <span class="va">D</span>, </span>
<span>    subset <span class="op">=</span> <span class="va">X</span> <span class="op">&gt;</span> <span class="op">-</span><span class="fl">1</span><span class="op">*</span><span class="va">bandwidth</span> <span class="op">&amp;</span> <span class="va">X</span> <span class="op">&lt;</span> <span class="va">bandwidth</span>,</span>
<span>    .method <span class="op">=</span> <span class="va">lm_robust</span>, </span>
<span>    inquiry <span class="op">=</span> <span class="st">"LATE"</span>,</span>
<span>    label <span class="op">=</span> <span class="st">"linear"</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="lem-ch16num5" class="theorem lemma">
<p><span class="theorem-title"><strong>Diagnosis 16.5 </strong></span>Regression discontinuity diagnosis across varying bandwidths</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>diagnosis_16<span class="fl">.5</span> <span class="ot">&lt;-</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  declaration_16<span class="fl">.6</span> <span class="sc">|&gt;</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">redesign</span>(<span class="at">bandwidth =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">0.05</span>, <span class="at">to =</span> <span class="fl">0.5</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  diagnose_designs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-ch16num10" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="../figures/figure-16-10.svg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;16.10: Bias-variance tradeoff in bandwidth selection for the regression discontinuity design.</figcaption></figure>
</div>
</div>
<section id="design-examples-4" class="level3" data-number="16.5.1"><h3 data-number="16.5.1" class="anchored" data-anchor-id="design-examples-4">
<span class="header-section-number">16.5.1</span> Design examples</h3>
<ul>
<li><p><span class="citation" data-cites="Kirkland2021">Kirkland (<a href="../references.html#ref-Kirkland2021" role="doc-biblioref">2021</a>)</span> uses a regression discontinuity design to estimate the effect of just electing a mayor with a business background on infrastructure and redistribution spending.</p></li>
<li><p><span class="citation" data-cites="carnegie2017international">Carnegie and Samii (<a href="../references.html#ref-carnegie2017international" role="doc-biblioref">2019</a>)</span> uses a regression discontinuity design to compare countries that are just-eligible for lender status to those that are just-ineligible on human rights and democracy policies.</p></li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-angrist2008mostly" class="csl-entry" role="listitem">
Angrist, Joshua D., and Jörn-Steffen Pischke. 2008. <em>Mostly Harmless Econometrics: An Empiricist’s Companion</em>. Princeton: Princeton University Press.
</div>
<div id="ref-bateson_2012" class="csl-entry" role="listitem">
Bateson, Regina. 2012. <span>“Crime Victimization and Political Participation.”</span> <em>American Political Science Review</em> 106 (3): 570–87.
</div>
<div id="ref-BennettCheckel2015PT" class="csl-entry" role="listitem">
Bennett, Andrew, and Jeffrey Checkel. 2015. <span>“Process Tracing: From Philosophical Roots to Best Practices.”</span> In <em>Process Tracing: From Metaphor to Analytic Tool</em>, edited by Andrew Bennett and Jeffrey Checkel, 3–37. New York: Cambridge University Press.
</div>
<div id="ref-brady2004data" class="csl-entry" role="listitem">
Brady, Henry E. 2004. <span>“Data-Set Observations Versus Causal-Process Observations: The 2000 US Presidential Election.”</span> In <em>Rethinking Social Inquiry: Diverse Tools, Shared Standards</em>, 267–72. Lanham: Rowman &amp; Littlefield.
</div>
<div id="ref-calonico2014robust" class="csl-entry" role="listitem">
Calonico, Sebastian, Matias D Cattaneo, and Rocio Titiunik. 2014. <span>“Robust Nonparametric Confidence Intervals for Regression-Discontinuity Designs.”</span> <em>Econometrica</em> 82 (6): 2295–2326.
</div>
<div id="ref-carnegie2017international" class="csl-entry" role="listitem">
Carnegie, Allison, and Cyrus Samii. 2019. <span>“International Institutions and Political Liberalization: Evidence from the World Bank Loans Program.”</span> <em>British Journal of Political Science</em> 49 (4): 1357–79.
</div>
<div id="ref-Carreri2017" class="csl-entry" role="listitem">
Carreri, Maria, and Oeindrila Dube. 2017. <span>“Do Natural Resources Influence Who Comes to Power, and How?”</span> <em>The Journal of Politics</em> 79 (2): 502–18.
</div>
<div id="ref-chaisemartin" class="csl-entry" role="listitem">
Chaisemartin, Clément de, and Xavier d’Haultfoeuille. 2020. <span>“Two-Way Fixed Effects Estimators with Heterogeneous Treatment Effects.”</span> <em>American Economic Review</em> 110 (9): 2964–96.
</div>
<div id="ref-dawid2022bounding" class="csl-entry" role="listitem">
Dawid, Philip, Macartan Humphreys, and Monica Musio. 2022. <span>“Bounding Causes of Effects with Mediators.”</span> <em>Sociological Methods &amp; Research</em>.
</div>
<div id="ref-dunning2012natural" class="csl-entry" role="listitem">
Dunning, Thad. 2012. <em>Natural Experiments in the Social Sciences: A Design-Based Approach</em>. Cambridge, UK: Cambridge University Press.
</div>
<div id="ref-fairfield2017explicit" class="csl-entry" role="listitem">
Fairfield, Tasha, and Andrew E Charman. 2017. <span>“Explicit Bayesian Analysis for Process Tracing: Guidelines, Opportunities, and Caveats.”</span> <em>Political Analysis</em> 25 (3): 363–80.
</div>
<div id="ref-frangakis2002principal" class="csl-entry" role="listitem">
Frangakis, Constantine E., and Donald B Rubin. 2002. <span>“Principal Stratification in Causal Inference.”</span> <em>Biometrics</em> 58 (1): 21–29.
</div>
<div id="ref-humphreys2017qualitative" class="csl-entry" role="listitem">
Humphreys, Macartan, and Alan Jacobs. forthcoming. <em>Integrated Inferences</em>. Cambridge: Cambridge University Press.
</div>
<div id="ref-Kirkland2021" class="csl-entry" role="listitem">
Kirkland, Patricia A. 2021. <span>“Business Owners and Executives as Politicians: The Effect on Public Policy.”</span> <em>The Journal of Politics</em> 83 (4): 1652–68.
</div>
<div id="ref-nellis_siddiqui_2018" class="csl-entry" role="listitem">
Nellis, Gareth, and Niloufer Siddiqui. 2018. <span>“Secular Party Rule and Religious Violence in Pakistan.”</span> <em>American Political Science Review</em> 112 (1): 49–67.
</div>
<div id="ref-paglayan2019public" class="csl-entry" role="listitem">
Paglayan, Agustina S. 2019. <span>“Public-Sector Unions and the Size of Government.”</span> <em>American Journal of Political Science</em> 63 (1): 21–36.
</div>
<div id="ref-Prillaman2022" class="csl-entry" role="listitem">
Prillaman, Soledad Artiz. 2022. <span>“Strength in Numbers: How Women’s Groups Close India’s Political Gender Gap.”</span> <em>American Journal of Political Science</em>.
</div>
<div id="ref-REVKIN2020104981" class="csl-entry" role="listitem">
Revkin, Mara Redlich, and Ariel I. Ahram. 2020. <span>“Perspectives on the Rebel Social Contract: Exit, Voice, and Loyalty in the Islamic State in Iraq and Syria.”</span> <em>World Development</em> 132: 104981.
</div>
<div id="ref-snyder_borghard_2011" class="csl-entry" role="listitem">
Snyder, Jack, and Erica D. Borghard. 2011. <span>“The Cost of Empty Threats: A Penny, Not a Pound.”</span> <em>American Political Science Review</em> 105 (3): 437–56.
</div>
<div id="ref-Stokes2016" class="csl-entry" role="listitem">
Stokes, Leah C. 2016. <span>“Electoral Backlash Against Climate Policy: A Natural Experiment on Retrospective Voting and Local Resistance to Public Policy.”</span> <em>American Journal of Political Science</em> 60 (4): 958–74.
</div>
<div id="ref-thistlethwaite1960regression" class="csl-entry" role="listitem">
Thistlethwaite, Donald L., and Donald T. Campbell. 1960. <span>“Regression-Discontinuity Analysis: An Alternative to the Ex Post Facto Experiment.”</span> <em>Journal of Educational Psychology</em> 51 (6): 309.
</div>
<div id="ref-VanEvera1997" class="csl-entry" role="listitem">
Van Evera, Stephen. 1997. <em>Guide to Methods for Students of Political Science</em>. Ithaca: Cornell University Press.
</div>
</div>
</section></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>We are also interested in the opposite case sometimes: we have a unit that did not experience an event, and we want to know the causal effect of <em>not</em> having it. In this case, we need to guess what would have happened if the event did happen. The same tools apply in reverse.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>An alternative motivation for some designs that do not rely on continuity at the cutoff is called “local randomization”.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../library/observational-descriptive.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Observational : descriptive</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../library/experimental-descriptive.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Experimental : descriptive</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>