# Observational : causal

In an observational design, researchers do not themselves assign units to conditions; the natural processes of the world are responsible for the observed treatment conditions. Causal inference from observational research designs is the art of imagining what outcomes treated units would have expressed if they had not been treated -- and the outcomes of the untreated units if they had been treated. 

Observational causal inference is hard because it depends on the world generating just the right circumstances. Process tracing requires observation of just the right clues to the causal mystery. Selection-on-observables requires measurement of a set of variables that collectively close all the backdoor paths from treatment to outcome. A difference-in-difference design requires a very specific kind of over-time stability --- that untreated potential outcomes move exactly in parallel. Instrumental variables designs require nature to randomly assign something we can measure. Regression discontinuity designs requires a cutoff that determines who is treated and who is not that we can observe and understand.

These are five of the big observational causal research designs. Many additional innovative designs have been developed to try to estimate causal quantities from observational research designs. These generally seek clever innovations in $A$ in order to have as few assumptions on $M$ as possible. We refer readers to @angrist2008mostly and @dunning2012natural for excellent overviews of the design theory behind many of these methods.  