# Criticism  {.unnumbered}



```{r}
#| echo: false
#| include: false
#| purl:  false
source("scripts/before_chapter_script.R")
```

A vital part of the research design process is gathering criticism and feedback from others. Timing is delicate here. Asking for comments on an underdeveloped project can sometimes lead to brainstorming sessions about what research questions one might look into. Such unstructured sessions can be quite useful but essentially restarts the research design lifecycle from the beginning. Sharing work only after a full draft has been produced is worse since the data strategy will have already yielded the realized data. The investigators may have become attached to favored answer strategies and interpretations. While critics can always suggest changes to *I* and *A* post-data collection, an almost-finished project is fundamentally constrained by the data strategy as it was implemented.

The best moments to seek advice come before registering preanalysis plans or, if not writing a PAP, before implementing major data strategy elements. The point is not to seek advice exclusively on sampling, assignment, or measurement procedures; the important thing is that there's still time to modify those design elements (Principle @exm-designearly: Design early). Feedback about the design as a whole can inform changes to the data strategy before it is set in stone.

Feedback will come in many forms. Sometimes the comments are directly about diagnosands. The critic may think the design has too many arms and won't be well-powered for many inquiries. Or they may be concerned about bias due to excludability violations or selection issues. These comments are especially useful because they can easily be incorporated in design diagnosis and redesign exercises.

Other comments are harder to pin down. A fruitful exercise in such cases is to understand how the criticism fits in to *M*, *I*, *D*, and *A*. Comments like, "I'm concerned about external validity here" might seem to be about the data strategy. If the units were not randomly sampled from some well-specified population, we can't generalize from the sample to the population. But if the inquiry is not actually a population quantity, then this inability to use sample data to estimate a population quantity is irrelevant. The question then becomes whether knowing the answer to your sample inquiry helps make theoretical progress or whether we need to generalize -- to switch the inquiry to the population quantity to make headway. Critics will not usually be specific about how their criticism relates to each element of design, so it is up to the criticism-seeker to understand the implications for design.

Sometimes we seek feedback from smart people, but they do not immediately understand the design setting. If the critic hasn't absorbed or taken into account important features of the design, their recommendations and amendments may be off-base. For this reason, it's important to communicate the design features -- the model, inquiry, data strategy, and answer strategy -- at a high enough level of detail that the critic is up to speed before passing judgment. 

