on:
  push:
    branches: main
  pull_request:
    branches: main

name: Render and deploy Book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
          # uncomment below and fill to pin a version
          # version: 0.9.105

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 7

      # - name: Install remotes
      #   run: |
      #      remotes::install_github("acoppock/vayr", auth_token = "${{ secrets.GITHUB_TOKEN }}")
      #      remotes::install_github("DeclareDesign/dddag", auth_token = "${{ secrets.GITHUB_TOKEN }}")
      #      remotes::install_github("cran/randnet", auth_token = "${{ secrets.GITHUB_TOKEN }}")
      #      remotes::install_github("szonszein/interference", auth_token = "${{ secrets.GITHUB_TOKEN }}")
      #      remotes::install_github("DeclareDesign/rdss", auth_token = "${{ secrets.GITHUB_TOKEN }}")
      #   shell: Rscript {0}

      - name: Prep Dropbox files
        run: |
          mkdir ~/Dropbox
          mkdir ~/Dropbox/DeclareDesign_book_rfiles
          wget -O ~/Dropbox/files.zip https://www.dropbox.com/sh/fqjlu8k90sx6kv8/AADcmSxqO35f4LEvHyJjl1Dwa?dl=1
          unzip ~/Dropbox/files.zip -d ~/Dropbox/DeclareDesign_book_rfiles -x /

      - name: Render book to all formats
        # Add any command line argument needed
        run: |
          quarto render --to html

      - name: Deploy 🚀
        # only deploy when push to main
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: _book
